### ISSUE TITLE
$scope binding is not working

### ISSUE THREAD

**Issue by ankur0101** [ocombe/ocLazyLoad#100]
Hi,
I have routes as :
```js
.state('dashboard', {
            url: "/dashboard",
            resolve: {
                deps: ['$ocLazyLoad',
                    function( $ocLazyLoad ){
                        return $ocLazyLoad.load({
                            name: "myApp",
                            files: ['src/dashboard/dashboardController.js']
                        });
                    }
                ]
            },
            templateUrl: "src/dashboard/partials/dashboard.html",
            data: { pageTitle: 'Dashboard' }
        })
```
and html template as 
```html
<div class="app-content" ng-controller="dashboardController" ng-init="loadDashboard()">
    <div ui-butterbar></div>
    <a href class="off-screen-toggle hide" ui-toggle-class="off-screen" data-target=".app-aside" ></a>
    <div class="app-content-body fade-in-up">

        <div class="bg-light lter b-b wrapper-md clearfix">
            <h1 class="m-n font-thin h3" style="float: left;">Dashboard - {{dashboard}}</h1>
        </div>
</div>
</div>
```
and controller as 
```js
'use strict';
tvp.controller('dashboardController', ['$scope', '$http', '$state', '$stateParams', function($scope, $http, $state, $stateParams) {
    $scope.dashboard = "Dashboard";
    $scope.loadDashboard = function() {
        console.log("Dashboard loaded");
    };
}]);
```
In html, I am using `ng-controller="dashboardController"` and so not using `controller: dashboardController` in ui-router.
After successful login, I get forwarded to dashboard but get `Dashboard - {{dashboard}}` on screen
In console, I get error as 
`Error: [ng:areq] http://errors.angularjs.org/1.2.26/ng/areq?p0=dashboardController&p1=not%20aNaNunction%2C%20got%20undefined`

But if I refresh the page, then issue solves, I see Dashboard - Dashboard and no error message in console.

However If I add `controller: dashboardController` in ui-route and remove `ng-controller="dashboardController"` from html, it gives following error

`Error: [ng:areq] http://errors.angularjs.org/1.2.26/ng/areq?p0=dashboardController&p1=not%20aNaNunction%2C%20got%20undefined`

I am not using requireJS, simple oclazyload. My angular version is 1.2.26

**Comment by curlyfro** [comment]
i had this problem too.  you need to change your module definition to: 
angular.module('myApp', []).  this will work.

**Comment by ocombe** [comment]
Thanks :)

**Comment by ankur0101** [comment]
Sorry for my late reply.
Things started working as expected after I wrote following line of code.

```javascript
.config(['$controllerProvider','$compileProvider','$filterProvider','$provide',function($controllerProvider,$compileProvider,$filterProvider,$provide){
        myApp.controller = $controllerProvider.register;
        myApp.directive  = $compileProvider.directive;
        myApp.filter     = $filterProvider.register;
        myApp.factory    = $provide.factory;
        myApp.service    = $provide.service;
        myApp.constant   = $provide.constant;
        myApp.value      = $provide.value;
    }])
```

But this code was not provided in any documentation of oclazyload.

**Comment by dolphub** [comment]
@ankur0101 Literally copy pasting that last config fixed all of my problems with this. Thanks!
