### ISSUE TITLE
ocLazyload will load already loaded component if application is launched by angular.bootstrap 

### ISSUE THREAD

**Issue by merlinchen** [ocombe/ocLazyLoad#109]
I put a simple example in this [plunker](http://plnkr.co/edit/1cVhD26T7vtnkWeuG9ql?p=preview) to illustrate the problem.

The application and `lazyloadModule` both require 'sharedModule'.

``` javascript
angular.module('sharedModule', [])
    .directive('sharedDirective', [function () {
        return {
            restrict: 'A',
            link: function () {}
        }
    }]);
```

But when loading `lazyloadModule`, the debug log illustrates that ocLazyLoad loaded `sharedDirective` again.

```
ocLazyLoad.fileLoaded lazyload-module.js
angular.js:11500 ocLazyLoad.componentLoaded ["sharedModule", "directive", "sharedDirective"]
angular.js:11500 ocLazyLoad.moduleReloaded sharedModule
angular.js:11500 ocLazyLoad.moduleLoaded lazyloadModule
```

The confusing part is if i put `sharedDirective` in a sub module which required by `sharedModule` like this:

``` javascript
angular.module('sharedModule', ['sharedModuleSub']);
angular.module('sharedModuleSub', [])
    .directive('sharedDirective', [function () {
        return {
            restrict: 'A',
            link: function () {}
        }
    }]);
```

Then everything works fine.

The behavior described in this issue will only happen if the application is launched by `angular.bootstrap`

**Comment by iamwebdesigner** [comment]
I am facing the same issue in version 1.0.6. I am trying to load angular.ui modules by ocLazyLoad but it gives error for multiple declaration of directives. How can I solve this problem?
