### ISSUE TITLE
How to include in grunt task the specifically lazy loaded files?

### ISSUE THREAD

**Issue by harshal-avantsoft** [ocombe/ocLazyLoad#110]
Hi,

I'm using grunt to create my production version of the project and that includes all the JS files mentioned in my index.html file. but for lazy load we define different modules files and there we define the bower_components and other required js files which needs to be in scripts directory and if its a dynamic path of the files then it's good for us.

thanks

**Comment by harshal-avantsoft** [comment]
GruntJS is a task runner and that create a process of tasks we define. I use it to minimise and concat the js files after my development updates to migrate my project to production version. The grunt task is automate to build & concat all js files mentioned in index.html, but using ocLazyLoad we define the JS files path like bower_components or some other third party libraries in some JS class.

So, now if I build for production it will not include any file mentioned in lazy loaded files, so can anybody have idea how to fetch/recognise these using grunt and it should be automatically picked as developer will not add the items into list if any new class is defined.

I think now this will clear your doubt.

**Comment by ocombe** [comment]
Ok I see. The lib doesn't know if you used gruntJS or not.
What you can do is define a variable and only use $ocLazyLoad if this variable isn't defined. Put this variable in one of the files that is concatenated by grunt.
But you'll have to adapt your code anyway.

**Comment by dhirenrouterabbit** [comment]
I know it's closed. I wrote article & created a demo application which might help you for the same https://goo.gl/aEUWVt . I am converting existing yeoman based AngularJS application to lazy load with Gruntfile modification.
