### ISSUE TITLE
Update ocLazyLoad links with the revised links created by grunt-rev

### ISSUE THREAD

**Issue by ritz078** [ocombe/ocLazyLoad#112]
I am using yeoman (angular-fullstack) for my project. I want to use ocLazyLoad (link) in it with grunt-rev. But how do I update the asset links written in the js files by the new filenames created by grunt rev ? The links in the html file are update but how do I update the links in js file?

**Comment by ocombe** [comment]
Hi, I have no idea, it's probably something that you should ask in the grunt-rev repository :)
