### ISSUE TITLE
User agent issue with phantomJS

### ISSUE THREAD

**Issue by redders6600** [ocombe/ocLazyLoad#114]
I'm using phantomJS to screenshot a page that uses ocLazyLoad, but the user agent code used to detect the browser version is causing an error in my case.

The userAgent string coming out of phatomJS is `Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.0 Safari/534.34`

The problem is, this contains the word `safari`, but doesn't contain a version, which means [this line](https://github.com/ocombe/ocLazyLoad/blob/e3bf1d25408badde748d25b2e7c114b5ed0ff96a/src/ocLazyLoad.js#L142) throws an error.

Perhaps the UA sniffing can be a bit more lenient if the string doesn't match the assumed format?

**Comment by redders6600** [comment]
Note this isn't a massive issue because it's possible to configure the user agent in phantomjs, so it's easy to workaround.

**Comment by ocombe** [comment]
Yes this should be fixed, thanks for the report!

**Comment by ocombe** [comment]
Fixed in #121 ! Thanks @websirnik for the PR
