### ISSUE TITLE
Possible to decouple injector and loader?

### ISSUE THREAD

**Issue by amcdnl** [ocombe/ocLazyLoad#115]
I use Require with OCLazyLoader.  Is it possible to decouple the loader from the injector for people that are using other loaders ( require/etc ) to make the package lighter.  Thoughts?

**Comment by ocombe** [comment]
Sure, if you do something like that:
```js
$ocLazyLoadProvider.config({
    jsLoader: requirejs
});
```

and that people don't use requirejs, it will be undefined and ocLazyLoad should switch to the native loaders included into the library.

**Comment by BenBlazely** [comment]
Hmm, my understanding of the question was more;

"If I'm using requireJS, can I remove the native loaders to make oc.LazyLoad lighter?"

**Comment by ocombe** [comment]
Ahhh ok! It makes more sense :P
I could make a light version yes, let me see what I can do.

**Comment by BenBlazely** [comment]
Not sure there will be much saving there to be honest. At a very quick glance, maybe 70 loc?

**Comment by BenBlazely** [comment]
I wonder actually whether it would be better to break out the loaders into their own file for the sake of maintainability vs a 'lite' version that needs to be kept up to date.

I use angular-translate quite a bit which has a similar approach for it's language template loaders. They're not included by default, you have to load the one you want separately.

It would be a breaking change however, but food for thought!

**Comment by amcdnl** [comment]
@BenBlazely - I like that idea.

**Comment by ocombe** [comment]
Yes me too, it makes sense and it would probably allow more loaders to emerge (I'm thinking about SystemJS here for example).
This would of course be included in a major release.

@PascalPrecht in retrospective do you think that making parts of angular-translate separate components was a good idea ? Or was it more trouble than it was worth ?

**Comment by amcdnl** [comment]
@ocombe Yes, I'm migrating from require to system ; hints the question ;)

**Comment by mr-moon** [comment]
@amcdnl I am. You can check out link I provided in comments of #118 . You can see the working example. The technique of `ocLazyLoad` is used in `app/loader/module.js` file.

**Comment by amcdnl** [comment]
@mr-moon Ya, I got it working ... Check it out here: https://github.com/amcdnl/systemjs-test

**Comment by ocombe** [comment]
Ohh this is awesome @amcdnl, I wanted to do something like this, thanks!
I'll take a look and see if I need to update the lib to make it more user-friendly

**Comment by amcdnl** [comment]
Ya, it wasn't easy to get it all working right....

Take a look in the `routes.js` file to see how I lazy load the modules based on future states defined in the json file.  I think if we could just decouple the injector code that would work pretty nice.

Also worth mentioning, I found this project the other day: https://github.com/robianmcd/angular-next

**Comment by ocombe** [comment]
Yes this is sexy, I might mention you in my conf at ng-nl if you don't mind :)
The angular-next project also looks really promising, thanks

**Comment by amcdnl** [comment]
Not at all .... are you going to ng-conf in Utah?

**Comment by ocombe** [comment]
I wished, but it would cost too much (I'm in France, that's a long trip). Besides, I already went to ng-europe and now ng-nl, that's enough conferences for now :)

**Comment by amcdnl** [comment]
@ocombe ya, thats quite a few.  I'll be at ngconf only reason I asked.  So back on topic, could u give me some pointers to where I should get started trimming the lib for this solution?

**Comment by ocombe** [comment]
Hmm not really, it's probably something that I should make myself :)
I'll try to do it next week.

**Comment by amcdnl** [comment]
:) Right on!  Look forward to seeing it.

**Comment by ocombe** [comment]
This is on the roadmap for 1.0 https://github.com/ocombe/ocLazyLoad/issues/139
