### ISSUE TITLE
Improvement: can you separate and isolate loading from registering?

### ISSUE THREAD

**Issue by mr-moon** [ocombe/ocLazyLoad#118]
The biggest limitation of `ocLazyLoad` is it's built-in loading mechanics. Even though we could use plain async loader, we can't really benefit from AMD-like loaders.

We define modules like:
```
// app.js:
myDefine(['services'], function () {
    return angular.module('app', ['services']);
});

// services.js:
myDefine([], function () {
    return angula.module('services', []);
});
```

Then dependency resolution kicks-in and does it's job. But we can't really stitch it with `ocLazyLoad`.

Can I suggest something like:
```
<script src="ocLazyLoad.js"></script>
<script src="ocLazyLoad.register.js"></script>
<script src="ocLazyLoad.load.module.js"></script>
<script src="ocLazyLoad.load.script.js"></script>
<script src="ocLazyLoad.load.css.js"></script>
<script src="ocLazyLoad.directive.js"></script>
```

Or even aggregating `load.*.js` into single `load.js`. The point is, module registration is quite complex on it's own, and if we could really separate it's API from everything else — the application spectre will grow exponentially.

Any thoughts?

**Comment by ocombe** [comment]
Your request is kinda similar to this: https://github.com/ocombe/ocLazyLoad/issues/115
I will implement separate loaders as plugins so that users can use the one they want without impacting the file size, and it will also make the development of new loaders easier.
But why would you want to externalize the register / module / directive parts? I don't get what the benefit would be?

**Comment by mr-moon** [comment]
@ocombe oh, thx. No, I'm not particularly after externalizing those.. Just if we're saving filesize and organizing our dependencies, we could take out as much as possible. 

Here I've implemented only `register` and `invokeQueue` functions (look at `app/loader/module.js` file) and it works well: http://cl.ly/0w041y3e3P0n (sorry, plunker doesn't work with my AMD loader) make code clean and without unused lines of code.

**Comment by ocombe** [comment]
It's true that if I externalize those parts, anyone could just use this for its own plugins, that could be useful.

**Comment by ocombe** [comment]
This is on the roadmap for 1.0 https://github.com/ocombe/ocLazyLoad/issues/139
