### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by miganga** [ocombe/ocLazyLoad#125]
Is there a way to inject css dependencies before the main css file in the head file?

**Comment by ocombe** [comment]
If you mean that you want to insert the css file before in the dom, yes it is possible :

The files, by default, will be inserted before the last child of the head element. You can override this by using insertBefore: 'cssSelector':

```js
$ocLazyLoad.load({
    name: 'TestModule',
    insertBefore: '#load_css_before',
    files: ['bower_components/bootstrap/dist/css/bootstrap.css']
});
```

Give an id to your style tag, and use this to insert before.

**Comment by miganga** [comment]
Would this work for style tag?

**Comment by miganga** [comment]
Sorry I meant link tag

**Comment by ocombe** [comment]
Yes sure, you don't even need to use an id, you can use the src as an attribute if you want :)
Any css selector supported by angular (and jquery if you use it) will work.

**Comment by miganga** [comment]
Being level headed here :)  For this below,

<link href="app/css/base.css" rel="stylesheet" id="load_before">

$ocLazyLoad.load({
    name: 'TestModule',
    insertBefore: 'load_before',
    files: ['bower_components/bootstrap/dist/css/bootstrap.css']
});

Should Work?

**Comment by ocombe** [comment]
This would be:

```js
$ocLazyLoad.load({
  name: 'TestModule',
  insertBefore: '#load_before',
  files: ['bower_components/bootstrap/dist/css/bootstrap.css']
});
```

And if you use the href attribute:
```js
$ocLazyLoad.load({
  name: 'TestModule',
  insertBefore: '[href="app/css/base.css"]',
  files: ['bower_components/bootstrap/dist/css/bootstrap.css']
});
```

**Comment by miganga** [comment]
Ok, when I involve resolve:, it seems not to work.

**Comment by miganga** [comment]
Can I plug it in into the config file?

**Comment by ocombe** [comment]
Hmm no it's a load parameter only.

**Comment by miganga** [comment]
Ok, I figured it out.  I had a constant where I read all files needed to be loaded through a function.  Just modded that.  Thanks again. Great feedback as usual.

**Comment by ocombe** [comment]
Anytime! :+1:
