### ISSUE TITLE
Is it possible to load css files in <Head> tag and js files in <body> tag

### ISSUE THREAD

**Issue by HemanthKona** [ocombe/ocLazyLoad#126]
Right now link or script tags are getting appended to head tag. 

So what I want to achieve is
- append link or load css files in head
- append script or load js files in body

Any help will be appreciated. Let me if you need more explanation for my issue.

**Comment by ocombe** [comment]
The files, by default, will be inserted before the last child of the head element. You can override this by using insertBefore: 'cssSelector':

```js
$ocLazyLoad.load({
    name: 'TestModule',
    insertBefore: '#load_css_before',
    files: ['bower_components/bootstrap/dist/css/bootstrap.css']
});
```

So in your case you will have to use the `insertBefore` parameter for all js files.

Another possibility for you is to define your own jsLoader in the config, and change how it works.
This way you won't have to use insertBefore anytime you load a js file.
You might want to copy the one from the src file and adapt it to your needs.

**Comment by HemanthKona** [comment]
Thanks a lot for replying.
My files array has css and js files. like below. 
```javascript
files: [
    '../assets/css/modules/test.css',
    '../modules/accounting/test.js',
]
```
Adding the below line to switch statement solved the issue for me.
`anchor = document.getElementsByTagName('body')[0];`

I'm adding the code block below for other people with same issue
```javascript
switch() {
case 'js':
    el = document.createElement('script');
    el.src = params.cache === false ? cacheBuster(path) : path;
    anchor = document.getElementsByTagName('body')[0];
}
```

Thanks again.
