### ISSUE TITLE
Controller got undefined

### ISSUE THREAD

**Issue by dud3** [ocombe/ocLazyLoad#130]
Hi, Sorry for bother, and hope it's not a silly question.

I have the following example:
<b>XController.js</b>
```js
angular.module('XModule', ['oc.lazyLoad'])
	.controller('XController',  function ($scope, $window, $ocLazyLoad) {

   $ocLazyLoad.load({
      name: "YModule",
      files: ["/path/to/controller/YController.js"]
    }).then(function() {
      // Then just resolve the promise.
    }, function(e) {
      console.log(e);
    });
...
});
```

<b>YController.js</b>
```js
angular.module('YModule', ['oc.lazyLoad'])
	.controller('YController',  function ($scope, $window, $ocLazyLoad) {
...
});

```

<b>HTML:</b>
```html
<script src="/path/to/app.js">
<script src="/path/to/XController.js">

<!-- This one works good -->
<div ng-controller="XController">
  <!-- This one called by $ocLazyLoad get~s undefined -->
   <div ng-controller="YController">

   </div>
</div>
```

The ``YController`` get's loaded successfully, but get's undefined ?

Thank you.

cc @ocombe

**Comment by ocombe** [comment]
If the div `<div ng-controller="YController">` is already in the dom before you lazy load the file, you need to either use the directive oc-lazy-load to wrap the bloc, or use an ng-if or ng-include that will create this part of the dom after the controller has been lazy loaded.

**Comment by dud3** [comment]
@ocombe 
I've now included through directive:
```js
<div ng-controller="YController" oc-lazy-load="{name: 'YModule', files: ['/path/to/controller/YController.js']}">...
```

Now the controller doesn't get undefined, but the problem is that, none of the function defined in that controller work:
```js
angular.module('YModule', ['oc.lazyLoad'])
    .controller('YController',  function ($scope, $window, $ocLazyLoad) {
   $scope.test_func() {
    alert("test");
  }
});
```

```js
<div ng-controller="YController" oc-lazy-load="{name: 'YModule', files: ['/path/to/controller/YController.js']}">
  <button ng-click="test_func()">Test</button>
</div>
```

Sorry for bothering again :D>.

**Comment by ocombe** [comment]
the oc-lazy-load directive should be defined in a div around the ng-controller one :)

```html
<div oc-lazy-load="{name: 'YModule', files: ['/path/to/controller/YController.js']}">
    <div ng-controller="YController">...</div>
</div>
```

**Comment by dud3** [comment]
Uhh Sorry my bad, everything works fine now :D>.

Thank you so much.

**Comment by ocombe** [comment]
No problem, have fun :)

**Comment by dud3** [comment]
@ocombe Sorry for bothering again, just one more final question: in this particular case, is there any way of lazy loading files from ``js`` file instead ?

**Comment by ocombe** [comment]
Yes, you will have to use $compile (check the angular doc) to parse the html that already includes the directives you just lazy loaded.
You can also use ng-include with a partial to only include that part of DOM when the files have been lazy loaded.

**Comment by dud3** [comment]
Thanks a lot.
