### ISSUE TITLE
Loading modules with css files fails when using together with Awesomium.Net

### ISSUE THREAD

**Issue by sjoerd222888** [ocombe/ocLazyLoad#131]
Using ocLazyLoad together with Awesomium (1.7.5.0) (http://www.awesomium.com) does not work if there is a css file in the files array. The promise gets resolved but the ng module does not work. I have posted a minmal example on stackoverflow: http://stackoverflow.com/questions/28541731/lazyloading-angularjs-module-with-css-file-fails-with-awesomium-web-view

To reproduce you need to install the Awesomium sample that are shipped with the SDK (for Windows), see: http://www.awesomium.com/download.

As it does work on all browser expect Awesomium I suppose it's a bug on their side, but I am not sure of course. OcLazyLoad does also not throw any error. Is there anything interesting that can be tested to narrow down the cause of this issue?

**Comment by ocombe** [comment]
Hmm interesting, I'll check it out when I can.
Do you know if the script files are inserted into the DOM ? (they should be if the promise is resolved).

If you only try to lazyload the css file then what happens ?

**Comment by sjoerd222888** [comment]
All files (script and css) are inserted into the DOM.
If I only lazyload the css file then the styles get applied.

**Comment by ocombe** [comment]
Interesting, then I need to investigate because I have no idea what the problem is right now :)

**Comment by sjoerd222888** [comment]
Btw. apparently Awesomium build on top of the same core as Chrome 18. I determined the version using the method described here: http://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser 

I have tried to find this version but it seems very hard to find downloads for old versions. Unfortunately I did not succeed. As I use Awesomium actively I would be happy if this could be fixed. On the other hand the error could be due to a bug in this chromium version.

Do you already test the lib with browserstack?

**Comment by sjoerd222888** [comment]
I will try using another async loader.
