### ISSUE TITLE
Version on Lazy loaded file

### ISSUE THREAD

**Issue by dud3** [ocombe/ocLazyLoad#137]
I have the following:

```js
<div oc-lazy-load="{ name: 'app.submission', files: [ '/src/app/controllers/submissionCtrl.js?v=xy12' , '/src/app/factories/categoriesSvc.js' ] }">
```

The one with the version on `'/src/app/controllers/submissionCtrl.js?v=xy12'` doesn't load ?

Thank you in advance.

Hopefully I'm not asking a silly question.

cc @ocombe

**Comment by ocombe** [comment]
Hmm I don't know why no one ever reported this before, but the file type detection regexes don't take into account the file names with parameters at the end ("?v=xy12" in this case).
I'll fix it, in the mean time you can use:

```html
<div oc-lazy-load="{[ {path: '/src/app/controllers/submissionCtrl.js?v=xy12', type: 'js'} , '/src/app/factories/categoriesSvc.js' ]">
```

By the way, with ocLazyLoad 0.6.x you don't need to give the name of the module that you're lazyloading

**Comment by ocombe** [comment]
Ok thanks for the report, this is fixed!

**Comment by dud3** [comment]
+1.

**Comment by dud3** [comment]
Another quick question, did we happen to update the bower's file ?

**Comment by ocombe** [comment]
nop I didn't make a new release yet

**Comment by ocombe** [comment]
I've released 0.6.3 with this fix :)

**Comment by dud3** [comment]
Awesome, well thanks a lot :D>.

**Comment by ocombe** [comment]
No problem! I wanted to see if new bugs from the 0.6.x release would pop up so that I can put more fixes in this new release, but it looks stable now.
I've started working on the big refactoring for 1.0 now :)

**Comment by dud3** [comment]
That sounds even more awesome, looking forward to the big release :D>.
