### ISSUE TITLE
Angular 1.5 & ocLazyLoad

### ISSUE THREAD

**Issue by ocombe** [ocombe/ocLazyLoad#138]
@amcdnl [wrote](https://github.com/ocombe/ocLazyLoad/issues/135#issuecomment-77727965):
> @ocombe so I guess since 1.5 will have lazy-loading there is no need for ocLazyLoad in the near future :(

As you may know, Angular 1.5 will include the possibility of lazy loading components. The draft is [here](https://github.com/angular/angular.js/issues/11015).

The proposed implementation will be:
> The implementation would consist of a new method on Angular Modules and a new service.
You would register some placeholder in the injector. Then you use a service to add the provider later.

> The only change to the behavior of the injector is that trying to inject a service that only has a placeholder, and not a corresponding provider implementation will throw a new type of error. The injector is still synchronous. HTML that has already been compiled, will not be affected by newly loaded directives.

> To avoid situations where it's ambiguous which implementation of a module is used in an app, once an app has been bootstrapped, any modules that include a placeholder cannot be redefined. Trying to redefine a module like this will throw an error

> To avoid situations where it's ambiguous what is actually included in a module, once a module with placeholders has been included in a bootstrapped app, it cannot have new placeholders or providers added to it.

Scenarios that this won't cover:
- loading a module without knowing its name: let's say that you want a service, and you know that this service in defined in a module, but all you want is the service, then you don't really need to know the name of the module (since ocLazyLoad 0.6.0), just the name of the service

- loading a module without knowing the name of all its components (to be confirmed, but I think that the current implementation will force you to define placeholders for all the components of a module, which will be really tedious...)

- lazy loading, the implementation won't include the loaders so you will still need something to do that (requirejs, systemjs, or... ocLazyLoad)

- a lazy loading directive such as the one from ocLazyLoad that combine a loader & a call to $compile

- the simplicity: ocLazyLoad lets you lazy load with just a file url. With the new implementation from angular 1.5 you will have to define the placeholders, it means more code to write

Also I'm working on new things for ocLazyLoad such as:
- a node module to create a tree of dependencies and a list of all the routes of your modules: it will preconfigure ocLazyLoad and then just let you lazy load components by name, no need for you to remember where your files are. Also, if you lazy load a component/module that has dependencies, ocLazyLoad will be able to find them in external files !

- a better integration with systemjs. You can do it right know with ui router future states, but it requires more code. I'd like to do something that would just work, you wouldn't have to write anything more than "import ..." in ES6, and ocLazyLoad would automatically register new components loaded by systemjs

- a whole new integration with webpack based on the two developments above: this webpack module would be able to parse your files, find the angular modules & components and suggest to webpack how it should pack the files!

As you can see, ocLazyLoad will still be useful once Angular 1.5 is out :)

**Comment by amcdnl** [comment]
Wow, didn't think of those edge cases. I'm excited about your system integration!!!!!!

**Comment by lookfirst** [comment]
:+1: :+1: :+1:

**Comment by lookfirst** [comment]
I see that you're working on that angular issue too. I think if you can convince them to integrate your functionality directly into angular, that would be most ideal.

**Comment by ocombe** [comment]
They won't (I already asked them) because my solution can lead to unexpected results.
Also it's a hack :)

**Comment by lookfirst** [comment]
I guess my view is that it would less of a hack if it the functionality was integrated directly. No monkey patching angular.module/bootstrap(). ;-)

**Comment by ocombe** [comment]
Yes, but they say that it can lead to unexpected results that would be hard to debug.
It's debatable, should they add a better functionality that would be flawed and probably unfixable, or should they add a something that works but is less useful.

I guess that they prefer something with no bugs :)

**Comment by dmackerman** [comment]
Super looking forward to the SystemJS implementation! I punted on using this library because the future states and ui-router extras was just too much boilerplate for an existing app.

**Comment by amcdnl** [comment]
@dmackerman check out my implementation.  i've narrowed the gap somewhat.

**Comment by lookfirst** [comment]
@dmackerman listen to @amcdnl  =)

**Comment by ocombe** [comment]
Yep the work from @amcdnl is really good for systemjs :)

**Comment by yellow1912** [comment]
Given that this issue is very old already, what is the current status on this?

Angularjs 2 is still a bit far away, plus many 3rd party plugins wont be ready for it soon so we will get stuck with Angular 1 for at least another 6 months and in the mean time it would make much sense to find a solution for 1.x instead of waiting for 2.x to mature.

**Comment by ocombe** [comment]
They postponed the lazy loading part of angular 1.5 to an unknown version (probably never) :(

**Comment by amcdnl** [comment]
@ocombe I got the impression it wasn't gonna happen ever for 1.x and in my prototyping I'm not sure even if 2.x can do it.

**Comment by yellow1912** [comment]
Too sad. I'm keen on migrating to angular2 soon for the chance to use lazy load, but seems like it's stll a bit too early for this (even with the beta 2 version). I have too many angular 1 module right now. 

I wonder if there is any online demo that shows how angular 1 and 2 can run side by side? I have seen this mentioned lots of time without seeing any real world example

**Comment by amcdnl** [comment]
@yellow1912 A2 can not lazy load out of the box, I'm sure @ocombe could elaborate more though. 

I'd avoid the upgrade for now, the code d/l is like 700+ kb right now. They plan to trim it down by release but thats a lot of weight...and not to mention the moving target API.

**Comment by ocombe** [comment]
You can lazy load in Angular 2 but it's a bit tricky right now, I might work on a lib to do that one day (but I have many things on my plate right now).
Also they plan to pre-compile a lot of stuff to dump the template parser (to reduce the size), which means no more lazy loading.

@amcdnl I don't use gitter (and didn't receive any update?), you can find me on the angular buddies slack, or on gtalk (olivier.combe@gmail.com) or twitter

**Comment by brutalcrozt** [comment]
> @ocombe They postponed the lazy loading part of angular 1.5 to an unknown version (probably never) :(

what is the main reason for that? do you know?

**Comment by ocombe** [comment]
Lack of man power, and Angular 2 coming soon with the ability to lazy load

**Comment by jamendub** [comment]
Damn, i'm sad to hear that :(
