### ISSUE TITLE
Milestone 2.0 - Support for Angular 1.5

### ISSUE THREAD

**Issue by ocombe** [ocombe/ocLazyLoad#142]
- [x] Support for Angular 1.5

**Comment by daihuaye** [comment]
Hi @ocombe, how is the issue going? It has been a year now. Are you going to supported this? Thank you.

**Comment by ocombe** [comment]
1.5 should be supported, is it not the case for you ?

**Comment by fugwenna** [comment]
I am having an issue having my 1.5 component registering/rendering.  I've attempted with a non-lazy-loaded component, and that seemed to register/render fine.

The file is properly loaded, and it even hits my resolve without issue which I have defined on the state, but I can't narrow down why.

**Comment by fugwenna** [comment]
Having problems lazy loading components and having them properly register/render.  File is properly loading, but my component is not instantiating

**Comment by essivision** [comment]
Where is ocLazyLoad release for Angular 2.0 ?

**Comment by ocombe** [comment]
There is not need for ocLazyLoad in angular 2, because angular 2 supports lazy loading out of the box
