### ISSUE TITLE
Problems in IE8 with AngularJs-ie8 build

### ISSUE THREAD

**Issue by MarG22** [ocombe/ocLazyLoad#146]
I am using the Angularjs-ie8 build (v 1.3.13) (https://github.com/fergaldoyle/angular.js-ie8-builds) as well as ocLazyLoad and some polyfills. Everything is working fine for modern browsers, but it seems that in IE8 the only event triggering is fileLoaded. 

There are no errors in the console.

I apologise for the vagueness of the issue but I am pretty much lost and not as familiar as I should with ocLazyLoad (my colleagues developed this part of the app).

Any suggestions of how to debug this issue would be highly appreciated.

**Comment by ocombe** [comment]
I'll need to try with this ie8 build, my lib should work with angular 1.2.x and IE8 (last I checked), so I'm not sure the problem is entirely in my lib.

**Comment by MarG22** [comment]
Hi again. I am glad to say the problem is solved and it wasn't related to your library, which works fine with the special Angular build for IE8.
I am very sorry if I have made you work for nothing.
Thanks anyway for your quick response.

**Comment by ocombe** [comment]
No problem, glad you figured it out :)
