### ISSUE TITLE
Controlling modules

### ISSUE THREAD

**Issue by mohanr** [ocombe/ocLazyLoad#151]
This is a question. We have a big application. Eventhough we have module-specific loaders it only helps to modularize the code. We have no control over the module loader flow. We don't know how many modules are loaded when we view a screen. How do I have that type of control over the modules ? Can I unload modules if I don't need them ? Otherwise the browser will have all the code of the application which is not desired. Am I making sense ? Is there a script that looks at the queue and prints how many modules are loaded or unloaded ?

**Comment by ocombe** [comment]
Hi.
First of all, it is impossible to unload a module with Angular.
With ocLazyLoad you can use events to monitor what modules are loaded, and you have functions to get the list of loaded modules.

**Comment by lookfirst** [comment]
I probably wouldn't want to store any state within a module directly so they really shouldn't use up many resources. There is also listening for $destroy which cleans up module scopes.

**Comment by mohanr** [comment]
Thanks. I meant that the module also loads related code. So too much code
is loaded. So I can monitor $destroy and track what is eligible for GC ? I
compare this with the JVM GC. I also use Chrome tools.

**Comment by lookfirst** [comment]
If you're really worried about it you can also just load another url so the page refreshes and resets things. It is another network hit though.

**Comment by mohanr** [comment]
Which part of ocLazyLoad should I use to print the queue of modules?

**Comment by ocombe** [comment]
From the docs:
`getModules()`: Returns the list of loaded modules

---> `$ocLazyLoad.getModules()`
