### ISSUE TITLE
Url with hash fails to lazyload

### ISSUE THREAD

**Issue by websirnik** [ocombe/ocLazyLoad#153]
AddThis uses url with the hash to pass account ID to the javascript.
 
![screen_shot_2015-03-23_at_14_20_12_1](https://cloud.githubusercontent.com/assets/282871/6781758/e8c5337c-d167-11e4-9f7e-98ae6ba87cbc.png)

When I'm lazy-loading - `//s7.addthis.com/js/300/addthis_widget.js#pubid=MYID&domready=1` - there is no request being sent and ocLazyLoad promise returns success, even though nothing has loaded.

It used to work with 0.5.2. But not with the recent 0.6.3 and 1.0.0-alpha.

**Comment by ocombe** [comment]
Oh yes, I know where it comes from, sorry about that, I'll fix it tonight :)

**Comment by ocombe** [comment]
Fixed :)
