### ISSUE TITLE
1.0.0-alpha2 breaks due undefined 'require' var

### ISSUE THREAD

**Issue by websirnik** [ocombe/ocLazyLoad#154]
1.0.0-alpha1 was running fine. 1.0.0-alpha2 fails for me.

Angular throws `Uncaught ReferenceError: require is not defined`. For some reason there is no trace. 

A quick lookup for `require` led me to this: https://github.com/ocombe/ocLazyLoad/blob/ec079b08e7babf25365e060619445bce21234b17/dist/ocLazyLoad.js#L1164 

`require` is indeed undefined.

fiy I'm not using RequireJS.

**Comment by ocombe** [comment]
Thanks! :)
