### ISSUE TITLE
Components registered using object form in a lazy-loaded module are not loaded

### ISSUE THREAD

**Issue by mrcrowl** [ocombe/ocLazyLoad#156]
When we register directives in our lazy-loaded modules, we tend to use an object variable to hold all of the directives and then register them in one go.  Something like this:
```
var gameDirectives = {
   "gameStarLevel": GameStarLevel.directive, 
   "gameCrossbow": GameCrossbow.directive
}

angular.module("game", []).directive(gameDirectives);
```

Unfortunately, ocLazyLoader doesn't seem to recognise the object-form of component registration, and requires us to use this form:
```
angular.module("game", [])
    .directive("gameStarLevel", GameStarLevel.directive)
    .directive("gameCrossbow", GameCrossbow.directive);
```
See: http://plnkr.co/edit/DWaf9o1bZOHeTzk0FoQh?p=preview

**Comment by ocombe** [comment]
I've never seen such a thing, but according to [the documentation](https://docs.angularjs.org/api/ng/provider/$controllerProvider) it's real:
> name	(stringObject)
  Controller name, or an object map of controllers where the keys are the names and the values are the constructors.

I'll add the support for it if I can :)

**Comment by ocombe** [comment]
Fixed! Thanks for the report, I learned a new thing with this :)

**Comment by mrcrowl** [comment]
Thanks for the quick fix Oliver. Nice refactoring too.
