### ISSUE TITLE
unexpected application behavior when setting cache: false

### ISSUE THREAD

**Issue by emaish** [ocombe/ocLazyLoad#158]
I try to bring fresh controller js files each time a view is requested, so i set cache: false.
what happens is with each request a new file is injected to the page but the old files still there, and the application doesn't feel the changed contents from the new injected file, because it keep using the first loaded controller file

**Comment by ocombe** [comment]
Hmm yes, there is no way to make this work right now.
Anyway the controller will be loaded by angular and there is no way to unload it... :-/

The cache option makes more sense for templates or css files.
