### ISSUE TITLE
Controller not registering

### ISSUE THREAD

**Issue by warcops** [ocombe/ocLazyLoad#159]
Hi,

I am getting the following error message:
```
Error: [ng:areq] Argument 'HomeController' is not a function, got undefined
```
Following is the code for module:
```
var MyApp = angular.module("MyApp", [
    "ui.router",
    "oc.lazyLoad"
]);

CCApp.config(['$stateProvider', '$urlRouterProvider', '$ocLazyLoadProvider', function ($stateProvider, $urlRouterProvider, $ocLazyLoadProvider) {

    //Redirect any unmatched url
    $urlRouterProvider.otherwise("/");
    $stateProvider

    //home
    .state('home', {
        url: "/",
        templateUrl: "template/home/home-main.html",
        controller: "HomeController",
        resolve: {
            deps: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.load({
                    name: 'MyApp',
                    files: [
                            //TODO add all the required css and js

                            '../script/app/controllers/HomeController.js'
                        ]
                });
            }]
        }
    });

   $ocLazyLoadProvider.config({
      debug: true,
      events: true,
        loadedModules:['MyApp']
    });

}]);
```

The code in HomeController.js is as follows:
```
CCApp.controller('HomeController', ['$rootScope', '$scope', function($rootScope, $scope) {
    $scope.$on('$viewContentLoaded', function() {   
        //TODO logic for after view is loaded
    });
}]);
```

Following are the version details:

* AngularJS v1.3.15
* ocLazyLoad v1.0.0-alpha2

I am not sure what I am doing wrong here. A quick reply would be much appreciated.

**Comment by ocombe** [comment]
Hi, sorry for the long response time, I was in London.

I think that the problem is in your controller: `CCApp.controller( ....`, but CCApp isn't defined in your HomeController.js file.

Also, the config param `loadedModules` doesn't exist anymore, and the `name` parameter isn't required anymore.

I made you a plunkr with the edited files: http://plnkr.co/edit/iDqh7pdqyrmP4dGJU6u0?p=preview

**Comment by warcops** [comment]
Oh snap! I thought that the controller scope will propagate to HomeController. I guess I am still in the Global variable era.

Thanks for the quick response. Appreciate it. :)

**Comment by ocombe** [comment]
No problem (and it wasn't really that quick :P)

**Comment by mastermoin** [comment]
to continue with this in my code controller is define in respected JS, and JS is also loaded successfully but i am still getting error : 

Argument 'homeCtrl' is not a function, got undefined

**Comment by mastermoin** [comment]
i also tried issue no 182 and solution but not solve 

https://github.com/ocombe/ocLazyLoad/issues/182

see my controller on above issue comment

**Comment by warcops** [comment]
@mastermoin : why are you using require like syntax here? any specific reason?

**Comment by mastermoin** [comment]
ya this is mandatory to use requrejs

**Comment by warcops** [comment]
@mastermoin : i hope that the dependency tree paths and shims are proper. Coming back to the issue with ocLazyLoad. Can you please share the code with the app definition, where you are registering the controller to the app?

**Comment by mastermoin** [comment]
this app has been design without lazyload and my role is to add lazyload into it i can't share code the dependency is look good, controller js file  load well and show on chrome developer network tab but still throw error

**Comment by ocombe** [comment]
if you use requirejs, then you need to use the version of ocLazyLoad that works with requirejs: https://github.com/ocombe/ocLazyLoad/blob/master/dist/ocLazyLoad.require.js
Is this the case ?

**Comment by mastermoin** [comment]
i am injecting - ../lib/oclazyload/dist/ocLazyLoad.require' but still getting same problem

**Comment by ocombe** [comment]
Hmm your controller is really weird, I'm not a requireJS pro, but I'm pretty sure that you don't need to return anything.
Have you looked at the requirejs example?
https://github.com/ocombe/ocLazyLoad/tree/master/examples/requireJSExample

**Comment by mastermoin** [comment]
with oclazyload : controller wired
with oclazyload.require : controller is not wired 

lazyJs: ['$ocLazyLoad', function ($ocLazyLoad) {
                        return $ocLazyLoad.load({
                            files: [
                                'js/controllers/homeCtrl'
                            ]
                        });
                    }]

its try to get http://localhost:8081/js/js/controllers/homeCtrl.js

so its return error

**Comment by mastermoin** [comment]
try with all possible combination with JS file path but it is not wired

**Comment by mastermoin** [comment]
wired  by : path js/controllers/homeCtrl.js
but still error is same

**Comment by mastermoin** [comment]
its worked 
thanks man

**Comment by mastermoin** [comment]
dose this problem can be solve by promise

**Comment by warcops** [comment]
@mastermoin the reason for that is, that you are resolving the home controller in the require closure, which make the file aloof from the closure of angular. Angular has its own dependency management tool, I am not sure why require is coming into picture.

If you are bound to use only part of Angular, there are other libs like backbone, underscore and jquery which provide you with a require js compatible way to implement your functionality.
