### ISSUE TITLE
Webpack ui-router example

### ISSUE THREAD

**Issue by ay13** [ocombe/ocLazyLoad#161]
Is there an example using webpack and ui-router to load in chunks on states?

**Comment by ocombe** [comment]
Not yet, it's on the roadmap for 1.2: https://github.com/ocombe/ocLazyLoad/issues/141
You might wanna ask @kentcdodds for help on this, I think that he's got some insight.

**Comment by kentcdodds** [comment]
I actually haven't done lazy loading with webpack yet... But I don't expect it to be too difficult. I'd love to hear what you find!

**Comment by ay13** [comment]
I got it all working together in this repo. https://github.com/ay13/webpack-angular-oclazyload

**Comment by kentcdodds** [comment]
Looks awesome! I'll definitely look at this when I'm ready to do lazy
loading :-) Thanks.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ocombe** [comment]
You don't really need to call the load function, with 1.0.x you can use the function "inject" with the name of the loaded module: https://oclazyload.readme.io/v1.0/docs/oclazyload-service#additional-methods-
It was designed for people who load files using external loaders (such as require) :)

**Comment by ay13** [comment]
It uses npm for everything and ocLazyLaod is version 0.6.3 on npm. When npm gets the version bump I will update the repo.

**Comment by ocombe** [comment]
Ah yes, seems legit :-)
