### ISSUE TITLE
Usage in unit tests

### ISSUE THREAD

**Issue by scriby** [ocombe/ocLazyLoad#162]
I ran into a snag in an application I'm working on which uses oclazyload during some unit tests.

The crux of the problem is this line:

```
return instanceInjector ? instanceInjector : instanceInjector = $rootElement.data("$injector") || angular.injector();
```

The problem is that bootstrap doesn't occur during the tests, so there's no injector on the root element. It always ends up with a fresh injector, so any time it tries to run a config or run block it can't find the dependencies.

I am wondering if you had any thoughts about this scenario and the best way to handle it. I'm going to take a look at the test and if there's another way to do it as well.

**Comment by ocombe** [comment]
Well, you could manually set the injector on the rootElement like this: `$rootElement.data("$injector", injector)` with injector your instance of the injector ?

**Comment by scriby** [comment]
That's true, and that may be the best way to work around it (instead of kicking off a real bootstrap).

It would have saved me a few hours if oclazyload could have given a warning or something that it couldn't find the injector. It was a fairly difficult problem to track down.

**Comment by scriby** [comment]
I seem to be running into an issue with setting the $injector directly on the $rootElement. It works for the first test, but none after that. I think because it's an injector created by the unit tests, it gets "cleaned up", and oclazyload caches a reference to it, so it won't use the new one the next time around.

**Comment by ocombe** [comment]
Hmm yes, it keeps a cached version of it.
Is there a reason why you don't want to bootstrap your application ?

**Comment by scriby** [comment]
It seems a little weird to bootstrap from a unit test, but I don't think I mind too much.

I was able to get it going by just creating a div in a beforeEach and bootstrapping it (didn't even have to put it in the DOM). It's a bit roundabout, but oh well, at least it works :)

Maybe you can think about ways to make oclazyload easier to use from unit tests, or just drop a note in the docs if you think doing a manual bootstrap in a beforeEach is the best way.

**Comment by lookfirst** [comment]
I use angular mocks which provides the injector with `inject()`, here is a couple examples:

https://github.com/lookfirst/systemjs-seed/blob/master/test-unit/app/todo/directives/todoEscape.spec.js
https://github.com/lookfirst/systemjs-seed/blob/master/test-unit/app/todo/controllers/todoCtrl.spec.js

**Comment by scriby** [comment]
@lookfirst we are using angular mocks in a similar way to get the injector. The problem is more the interaction with oclazyload, since it doesn't use the same injector instance as the unit tests.

**Comment by lookfirst** [comment]
To be clear (and educate me a bit), is it that you're using ocLL within your angular modules? 

I'm trying to understand why ocLL is even being loaded for a unit test in the first place.

**Comment by scriby** [comment]
Yeah, the unit tests are actually testing out the router, which depends on ocLazyLoad.

**Comment by lookfirst** [comment]
I'd consider testing the router more of an integration test and do that as a protractor e2e test.

If you want to test the routing within a controller, you can do that like this:

https://github.com/lookfirst/systemjs-seed/blob/master/test-unit/app/todo/controllers/todoCtrl.spec.js#L72

**Comment by scriby** [comment]
Yeah, the router will definitely get hit in e2e tests.

It may be true that we simply shouldn't try to test the router from the jasmine / karma tests. However, I like doing as much as possible from them because they're so much faster and reliable compared to protractor / selenium tests.

**Comment by josepe36** [comment]
@lookfirst thanks a lots for your samples, very helpfull for me to understand the unit test.
Regards
