### ISSUE TITLE
Lazy loading particular components crashes the browser

### ISSUE THREAD

**Issue by Hubrus** [ocombe/ocLazyLoad#166]
Hi,

I have some modules like angular.strap and textAngular (bundled) that get lazy loaded using the directive, but since I've updated to 1.0.0-beta.1, the entire tab window (chrome) crashes when they get loaded. Before, with the 0.6.3 version everything was working (almost) ok. Are you aware of this problem?
I'll try to reproduce this problem in a plunkr as soon as possible, but till then, do you have any idea what can be the cause of this behavior?

Thanks!

**Comment by ocombe** [comment]
Hu that's weird! To crash it's probably an infinite loop or something... The plunkr would help for sure

**Comment by jermny** [comment]
I'm having a similar situation. I was running 0.5.2 with things just fine. I upgraded to 1.0.01-beta 1 (because I wanted to use Kendo) and if I have serie: true then I get into an infinite loop with:

if (params.serie) {
                    pushFile(params.files.shift());
                } else {

because the params.files never actually shifts appropriately and the array never shrinks. It shrinks initially then gets called again with the same values in files. I managed to find a way around this because I didn't end up needing serie: true so I set it to false. Still makes me nervous though.

**Comment by ocombe** [comment]
Oups, OK I see what the problem is, thanks

**Comment by datanotion** [comment]
Oh I'm glad you found it.  I was experiencing the same thing and was trying to track it down.  I didn't see the issue until I updated to the latest version of Kendo, so I thought it was a problem there.  Can't wait for the fix!  Thanks Oliver

**Comment by ocombe** [comment]
I'll take a look at it tonight if I can :)

**Comment by jermny** [comment]
Sounds great. Thank you for this fantastic product. I know what it's like
building something out for the community and it can be thankless and time
consuming. I just want to let you know that it is very much appreciated.

**Comment by ocombe** [comment]
Thanks!
The community has been great so far, no one ever complains when I accidentally add new bugs (such as this one) :P

**Comment by datanotion** [comment]
I have no doubt you will - you are all over this as usual.  Thanks for a great product.

If you find this is Kendo specific and you need the same help from me (like we setup before so you could track the bug) let me know.

And just as I'm typing this, the message from @jermny comes in - we think alike - fantastic product :)

**Comment by Hubrus** [comment]
I'm back with the plunkr: http://plnkr.co/edit/a9rTl5TgvdWGKXWenMRO :)
Thanks! :+1:

**Comment by ocombe** [comment]
Thanks for the plunkr.
The issue is caused by this commit: https://github.com/ocombe/ocLazyLoad/commit/6a5d3d4ca3fca1e90468aed10ef96f06669cd7f9
I need to find a better way to do this that would satisfy both issues

**Comment by ocombe** [comment]
Fixed! Checking another bug and I'll make a new release

**Comment by ocombe** [comment]
ok I released 1.0.0-beta.2

**Comment by Hubrus** [comment]
Nice! But now another problem appeared. If you put some simple text inside the element that uses oclazyload directive, you get "Syntax error, unrecognized expression: [Inner text]". See http://plnkr.co/edit/a9rTl5TgvdWGKXWenMRO?p=preview
This doesn't happen if you place an html element as child to the oclazyload directive div.
Not sure if is a real problem as this is not a real using scenario ... but still I was thinking to make you aware of this. :)

**Comment by ocombe** [comment]
Wow nice catch
Also you get an error if you don't have jquery.
Can you open another issue with this please ? I had to update the directive for another issue anyway :)
