### ISSUE TITLE
Issue whem text is specified as direct child inside oclazyload directive

### ISSUE THREAD

**Issue by Hubrus** [ocombe/ocLazyLoad#168]
As you requested, here is the issue :) 
If you put some simple text inside the element that uses oclazyload directive, you get "Syntax error, unrecognized expression: [Inner text]". See http://plnkr.co/edit/a9rTl5TgvdWGKXWenMRO?p=preview
This doesn't happen if you place an html element as child to the oclazyload directive div.
Not sure if is a real problem as this is not a real using scenario ... but still I was thinking to make you aware of this. :)

**Comment by ocombe** [comment]
Ok, it's fixed, thanks for the report :)
