### ISSUE TITLE
[Example] I wrote an fully example blog project for ocLazyLoad

### ISSUE THREAD

**Issue by lmk123** [ocombe/ocLazyLoad#169]
I like this lib very much ,so I wrote an fully example for ocLazyLoad : https://github.com/lmk123/demo-ocLazyLoad

I hope it will help other people :)

**Comment by ocombe** [comment]
Oups sorry I forgot to answer.
Thank you for taking the time to write an example, don't hesitate to add your project in the documentation (it's editable!) if you want it to be listed :)

**Comment by lmk123** [comment]
I found my example was not good enough, so I close this issue and I want to take some time to improve it firstly :)

**Comment by ocombe** [comment]
Ok no problem, let me know when it's better :)
