### ISSUE TITLE
Lazy load google maps api in router

### ISSUE THREAD

**Issue by rookiec14** [ocombe/ocLazyLoad#170]
Sorry if this is a beginners question. Other had similar questions here but I'm still not able to find how to get it to work.
It works fine when I do it like this:

    //include googleapis inside index.html
    ....
    <script src="https://maps.googleapis.com/maps/api/js?key=Mylongkey&libraries=places"></script>
    ...

    //and only lazy load the controller in $routeProvider inside routes.js
    ...
    .when('/map', {
    ...
        resolve: {
            loadModule: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.load([
                  'map.css',
                  'map.controller.js'
               ]);
          }]
       }
That works perfect.

Now if I try to lazyload the googleapi library in my router I get a ReferenceError: google is not defined.

    First attempt to lazy load googlemapsapi from my router:
    //routes.js
    ...
    .when('/map', {
        ...
        resolve: {
          loadModule: ['$ocLazyLoad', function ($ocLazyLoad) {
              return $ocLazyLoad.load([
                 'https://maps.googleapis.com/maps/api/js?key=Mylongkey&libraries=places',
                  'map.css',
                  'map.controller.js'
              ]);
          }]
        } 

    Second attempt to lazy load googlemapsapi from my router:
    //routes.js
    ...
    .when('/map', {
        ...
        resolve: {
          loadModule: ['$ocLazyLoad', function ($ocLazyLoad) {
              return $ocLazyLoad.load({
                  serie: true,
                  files: [
                      'https://maps.googleapis.com/maps/api/js?key=Mylongkey&libraries=places',
                      'map.css',
                      'map.controller.js'
                  ]
              });
          }]
        } 

    Third attempt to lazy load googlemapsapi from my router:
    //routes.js
    ...
    .when('/map', {
        ...
        resolve: {
          loadModule: ['$ocLazyLoad', function ($ocLazyLoad) {
              return $ocLazyLoad.load({
                  serie: true,
                  files: [
                      'https://maps.googleapis.com/maps/api/js?key=Mylongkey&libraries=places'
                   ]
              })
                 .then(function() {
                      return $ocLazyLoad.load([
                          'map.css',
                          'map.controller.js'
                     })
                });
          }]
        } 

I still get a ReferenceError: google is not defined.  The controller looks for google before it is ready.
Hope you could help or point me in the right direction. Thanks.

**Comment by ocombe** [comment]
Hmm I think that the third attempt should work, isn't it the case ?
I'd do it like this:
```js
.when('/map', {
    ...
    resolve: {
      loadModule: ['$ocLazyLoad', function ($ocLazyLoad) {
          return $ocLazyLoad.load({
             serie: true,
             files: [
               'https://maps.googleapis.com/maps/api/js?key=Mylongkey&libraries=places',
                'map.css',
                'map.controller.js'
             ]
          });
      }]
    } 
```

**Comment by rookiec14** [comment]
Thanks for your response. Maybe I'm doing something wrong but here is a [plunkr](http://plnkr.co/edit/7RVFkQIaBHrRMAPnmVmC?p=preview). (http://plnkr.co/edit/7RVFkQIaBHrRMAPnmVmC?p=preview). The console says, File type could not be determined, and Reference error google is not defined.  The controller looks for google but it is not ready.
     
    //But It works if not lazyloaded
    //delete the lazyloaded google api file so
    //app.js  will look like this
        ...
         return $ocLazyLoad.load({
                  serie: true,
                  files: [
                      'ctrl.js'                    
                  ]
           });

     //and then uncomment the google script in index.html like this
    //index.html
    ...
       <script src="https://maps.google.com/maps/api/js?sensor=false"></script>


Then the map appears!!

**Comment by ocombe** [comment]
to fix the file type, I changed this:
```js
files: [
  'https://maps.google.com/maps/api/js?sensor=false',
  'ctrl.js'                    
]
```
to
```js
files: [
  'js!https://maps.google.com/maps/api/js?sensor=false',
  'ctrl.js'                    
]
```

Because the url doesn't have a .js, (but /js), ocLazyLoad doesn't know that's it's a js file... (the regexp doesn't match). I used the requirejs syntax to say that's it's a js file.

But it won't do you no good because you will get the following error:
> Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

The file loaded from the url `https://maps.google.com/maps/api/js?sensor=false` does a document.write which you can only do when the DOM is loading, and not after...

Google map probably made a way to load the file asynchronously, you should check their documentation.

**Comment by lookfirst** [comment]
This may help: https://developers.google.com/maps/documentation/javascript/examples/map-simple-async

**Comment by ocombe** [comment]
yeah, that's probably what you should be using, thanks @lookfirst :)

**Comment by rookiec14** [comment]
Ok. Got it. Thanks so much. 
And great job making this labrary so easy to use.

**Comment by marcelolara** [comment]
I know that this is a closed issue, I've used it to solve my problem loading google maps api and I have created an example on github to share if someone serves you, @ocombe thanks for the library.

https://github.com/marcelolara/angularjs-loading-googlemaps-with-oclazyload

**Comment by ocombe** [comment]
Cool, thanks for taking the time to write this here ! I'm sure it might help other people :)

**Comment by phuyem** [comment]
This part is the most important (behind oclazy of course) : 

callback=initialize

initialize is a js function of yours which is ok to be "undefined"

Missing it won't make the map work
