### ISSUE TITLE
$ocLazyLoad.inject() throws Cannot read property 'reconfig' of undefined

### ISSUE THREAD

**Issue by erikmay1** [ocombe/ocLazyLoad#171]
When calling inject like this: $ocLazyLoad.inject(moduleName); "Cannot read property 'reconfig' of undefined" error is thrown.

Providing the default as follows seems to be a valid workaround: $ocLazyLoad.inject(moduleName, {reconfig: false});

Thanks

**Comment by ocombe** [comment]
Thanks, this is a bug that I need to fix :)

**Comment by ocombe** [comment]
It's fixed, thanks for the report, and sorry for taking so long :-/
