### ISSUE TITLE
Simplest way to lazy load a service into a controller

### ISSUE THREAD

**Issue by jml6m** [ocombe/ocLazyLoad#172]
Hi, I'm fairly new to Angular.js and this library, but I'm trying to lazy load a service in the simplest way possible. Is there a way to do it without a lot of code in `config()` and using `$stateProvider` and such? I'm building off the [Quick Start example](https://oclazyload.readme.io/v1.0/docs/getting-started).

Here's my shell code:

```html
<!-- HTML -->
<script type="text/ng-template" id="dialogTemplate">
      <div class="ngdialog-message">
        <h2>Congratulations, You Won!</h2>
      </div>
    </script>
```

```javascript
//JS
var app = angular.module("myApp", ["oc.lazyLoad"]);

app.controller('MyCtrl', function($scope, $ocLazyLoad) {
    //Lazy Loading
    $ocLazyLoad.load('ngDialog.js'); //This is located in same directory as app.js

    ngDialog.open({
                template: 'dialogTemplate'
            });
});
```
This gives me error: `ReferenceError: ngDialog is not defined`

I'm just looking to access the object I just loaded

**Comment by ocombe** [comment]
Hi, if you need to use it immediatly, you will have to use $injector:
```js
//JS
var app = angular.module("myApp", ["oc.lazyLoad"]);

app.controller('MyCtrl', function($scope, $ocLazyLoad, $injector) {
    //Lazy Loading
    $ocLazyLoad.load('ngDialog.js').then(function() {
        var ngDialog = $injector.get('ngDialog');
        ngDialog.open({
            template: 'dialogTemplate'
        });
    });
});
```

**Comment by jml6m** [comment]
Thanks, that works perfectly! It may help to add this information to the Quick Start page...

**Comment by ocombe** [comment]
Yes, I just added it to the FAQ :)

**Comment by crico** [comment]
I'm loading a dependecy with $ocLazyLoad and using ng-init in the view to start an action. The action must be executed after dependency is loaded as below, therefore, action is defined into the promise returned.

```javascript
$ocLazyLoad.load('dependency.js').then(function() {
        var myService = $injector.get('myService');

        $scope.initAction = function() {
            // execute myService
       };
    });
```

but for some reason, initAction is never executed. How I can do to make the methods defined in the scope to run?

**Comment by ocombe** [comment]
Like this ?

```js
$scope.initAction = function() {
    $ocLazyLoad.load('dependency.js').then(function() {
        var myService = $injector.get('myService');
        // execute myService
    });
};
```

**Comment by crico** [comment]
Hi @ocombe, 
First of all, great job.

My question is: why the method ng-init is not executed?
I'm invoking it  in my view and I'm defining the method into lazy-load promise return. If I define the method out lazy-load it is executed normally but before that lazy-load return...

**Comment by ocombe** [comment]
Well it depends on how you use it, but since it's async you have to take that into account :)

**Comment by amangupta38** [comment]
i'm using app.lazy.controller and getting an error for using lazy in it.
can you provide a required solution ?
