### ISSUE TITLE
URL Rewrite

### ISSUE THREAD

**Issue by vltr** [ocombe/ocLazyLoad#175]
It would be nice if I could rewrite all URLs given to .load() as a promise, the same way I can by adding an interceptor to $httpProvider. Any thoughts?

**Comment by ocombe** [comment]
The version 1.x of ocLazyLoad is modular, you can use decorators to overwrite (or add new) functions.
For example this is how you can define a jsLoader: https://github.com/ocombe/ocLazyLoad/blob/master/src/ocLazyLoad.loaders.jsLoader.js

In your case I'm not really sure what your intention is, do you have a use case for this ?

**Comment by vltr** [comment]
It's quite simple. I have a client-side rewrite engine, tied to my backend (because of the usage of aggressive-caching). So, 'include/state/topbar.html' becomes '/static/include/state/topbar.html?v=somehash'. It's not needed to rewrite the whole loader :)

**Comment by ocombe** [comment]
Ok, so you want to be able to intercept the url before it gets used.
If it's only for templates, the native template loader uses $http, so you can use interceptors.
If it's for js/css files, you might rewrite the loaders, their code is really short so it shouldn't be really difficult. And if you do so, maybe you could share them for others.
The js & css loaders could probably use $http, it shouldn't be too difficult, I didn't do it like this because you would have CORS issues (since it would use ajax instead of letting the browser load the files by itself).

**Comment by vltr** [comment]
Yeah, well, let me see if I can make myself clear. I'm already using $http interceptors for templates. They basically talks to the server using a websocket and returns the full URL of my template, which then I return as a promise. Now ... I was wondering how to do that with JS and CSS?

Just to illustrate:

```javascript
myApp.factory('myHttpInterceptor', ['$q', 'wsocket', function ($q, wsocket) {
    return {
        request : function (config) {
            var deferred = $q.defer();
            wsocket.send({
                method : 'get_static_url', // the command i want to execute in the server side, doesn't matter too much here
                data : config.url // the given url, let's say, 'includes/state/topbar.html'
            }, function (o) { // my callback (completely async)
                config.url = o.result; // o.result is the rewritten url, like '/static/includes/state/topbar.html?v=123456'
                deferred.resolve(config); // go on and make my day
            });
            return deferred.promise;
        }
    };
}]);

```

that's basically all. i'm trying to figure it out where I can do something similar with ocLazyLoad :)

**Comment by vltr** [comment]
I just made a fork of your project, let's see if I can add some "extra" modularity (if needed) ;)

**Comment by ocombe** [comment]
Cool, let me know if you need help !

**Comment by vltr** [comment]
Sure! Thanks a lot :)

**Comment by vltr** [comment]
Impossible for me to be more lamer ...

Before:
```javascript
        .state('index', {
            url: '/index',
            templateUrl: 'includes/states/main.html',
            controller: 'MainController',
            resolve: {
                loadMyCtrl: ['$ocLazyLoad', function ($ocLazyLoad) {
                        
                        return $ocLazyLoad.load({
                            files:
                            [
                                'vendors/some-plugin.js, // needs to be "rewritten"
                                'vendors/some-plugin.css', // need to be "rewritten" too
                            ]
                        });
                    }]
            }
        })
```

After:

```javascript
        .state('index', {
            url: '/index',
            templateUrl: 'includes/states/main.html',
            controller: 'MainController',
            resolve: {
                loadMyCtrl: ['$ocLazyLoad', 'wsocket', '$q', function ($ocLazyLoad, wsocket, $q) {
                        
                        var d = $q.defer();
                        wsocket.send({
                            method : 'get_bulk_static_url',
                            data : [
                                'vendors/some-plugin.js, // needs to be "rewritten"
                                'vendors/some-plugin.css', // need to be "rewritten" too
                            ]
                        }, function (o) {
                            d.resolve($ocLazyLoad.load({files : o.result}));
                        });
                        return d.promise;
                    }]
            }
        })
```

Done. No tricks needed. IMHO, it could make a good example, specially for ajs noobs like me (started messing around last monday, lol).

Anyway, thanks for your quick responses and help! :)

**Comment by ocombe** [comment]
Cool! So you didn't need to change ocLazyLoad after all :)

**Comment by vltr** [comment]
Yup, that moment you understand all that's needed for 'resolve' was a
deferred ... Shame on me, lol.
