### ISSUE TITLE
jsLoader incorrect signature when using requirejs

### ISSUE THREAD

**Issue by tony-vu** [ocombe/ocLazyLoad#178]
I've been using requirejs to dynamically load angular controllers/services/etc...  for a while but just recently added ocLazyLoad because of the ability to load modules as well. First I'd like to say thanks for the awesome work. Now here comes the issue:

I see that the jsLoader is being called with the following signature

```javascript
function (paths, callback, params)
```

and is expecting that the error (if any) is passed as the first parameter to the `callback`, but requirejs actually has the following signature

```javascript
function (deps, callback, errback, optional)`
```

In this case, `callback` is call with the return of the `define` function (if any) and `errback` will be called with an error object if an error has occurred. This leads to the following issue, If requirejs encounters an error (for example, a 404), then the promise is never resolved or rejected.

I've worked around this with adding the errback to jsLoader call as follows:

```javascript
if (jsFiles.length > 0) {
  var jsDeferred = $q.defer();
  $delegate.jsLoader(jsFiles, function (err) {
    if (angular.isDefined(err) && $delegate.jsLoader.hasOwnProperty("ocLazyLoadLoader")) {
      $delegate._$log.error(err);
      jsDeferred.reject(err);
    } else {
      jsDeferred.resolve();
    }
  }, function(err) {
    jsDeferred.reject(err);
  }, params);
  promises.push(jsDeferred.promise);
}
```

Please let me know what you think

**Comment by ocombe** [comment]
Well since the jsLoader is called internally, that shouldn't be a problem to change its signature yes, could you make a PR for that please ?

**Comment by tony-vu** [comment]
Sure thing...a PR request would be no problem. But before that I just want to be sure I got it right.

My work-around works for me because I'm specifically using requirejs. This change will break others who are using the included `ocLazyLoad` `jsLoader` since it's signature is in fact 

```javascript
function (paths, callback, params)
```

So I have 2 options
- 1) Along with the change to the internal call to jsLoader, I will also update the ocLazyLoad jsLoader signature to something like this:

```javascript
$delegate.jsLoader = function (paths, callback, errback, params) {
  var promises = [];
  angular.forEach(paths, function (path) {
    promises.push($delegate.buildElement("js", path, params));
  });
  $q.all(promises).then(function () {
    callback();
  }, function (err) {
    errback(err);
  });
};
```

or
- 2)  Keep the existing signature and create a wrapper around the requirejs loader. Maybe like so:

```javascript
$delegate.jsLoader = function(paths, callback, params) {
  var errback = function(err) {
    callback(err);
  }
  require(paths, callback, errback, params);
}
$delegate.jsLoader.requirejs = true;
```

To be honest I'm not completely satisfied with either approach. Option 1 makes ocLazyLoad a bit more requirejs centric whereas option 2 still leaves room for error (i.e., someone may expect the callback params to be the returns from the requirejs define calls).

Any thoughts on this or maybe even a third suggestion?

**Comment by Denich** [comment]
Hello,
Any updates here?

**Comment by ocombe** [comment]
Hmm I think that if you use oclazyload for requirejs it should work without anything else to do: https://github.com/ocombe/ocLazyLoad/blob/master/dist/ocLazyLoad.require.js
Unless you still have this problem ?

**Comment by tony-vu** [comment]
Submitted PR
