### ISSUE TITLE
better commonjs/es6 support

### ISSUE THREAD

**Issue by abhishekisnot** [ocombe/ocLazyLoad#179]
```import lazyLoad from 'oclazyload';```   gives me empty object. Then to add dependency in my angular app I have to use string dep -- ```var app = angular.module('myApp', [''oc.lazyLoad',]);```

It would be much better if oclazyload exported atleast a string:
```if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports)
{
  module.exports = 'oc.lazyLoad';
}```

Obviously there are multiple ways to better support commonjs/es6, but this I think is bare minimum approach.

**Comment by ocombe** [comment]
Yes, it was on my todo list for 1.0 and then I forgot to do it :)
Thanks

**Comment by olegskl** [comment]
Is this still on the todo list? :)

**Comment by ocombe** [comment]
Yes :)
But if you want to do a PR it will be merged much faster ;)

**Comment by olegskl** [comment]
I've added a very simple `module.exports` code almost copy-pasted from ui-router.
Do you need me to run the gulp release and commit dist changes as well?

**Comment by ocombe** [comment]
Thanks I'll do it! :)

**Comment by olegskl** [comment]
Do you have an ETA to push changes to npm? Thanks!

**Comment by ocombe** [comment]
I'd like to make some bug fixes before I release a new version, do you need this fast ?

**Comment by olegskl** [comment]
I think it's best to prioritize bug fixes than a fast npm release (btw I wasn't able to run Karma tests on my machine, failed with undefined angular).
We will install from github for the time being.

**Comment by ocombe** [comment]
Ok.
For the tests you need to install angular with bower

**Comment by olegskl** [comment]
Hah! That did the trick. :smiley:
