### ISSUE TITLE
Using oclazyload with $routeProvider giving controller is undefined.

### ISSUE THREAD

**Issue by pratikm23** [ocombe/ocLazyLoad#182]
Hi , 
I have removed the controller js file from the head section of my main html file in order to lazy load it.

I am using $routeProvider

    var app = angular.module('myApp', ['ngRoute','ngAnimate','oc.lazyLoad']);

    app.config(function ($routeProvider) {
    $routeProvider
        .when('/time',
            {
                controller: 'timeController', 
                templateUrl: '/app/partials/time.html',
                access: { requiredLogin: true },
                resolve: {
                    lazy: ['$ocLazyLoad', function($ocLazyLoad) {
                        return $ocLazyLoad.load([{
                            name: 'myApp',
                            files: ['/app/controllers/timeController.js']
                        }]);
                    }]
                }
            })

The file timeController.js is perfectly being loaded as i can see it in the network tab of browser console.
But still i am getting the error Argument 'timeController' is not a function, got undefined.

Plz help.

**Comment by ocombe** [comment]
Everything looks fine in this code. Do you have the code of the controller ?

**Comment by pratikm23** [comment]
app.controller('timeController', function ($scope, $http,$filter,$sce) {
        $scope.time = 'am';
    });

**Comment by ocombe** [comment]
Change `app.controller` by `angular.module('myApp').controller` :)

**Comment by pratikm23** [comment]
Yippee .. Thanks a lot!!!

**Comment by devonzara** [comment]
@ocombe, I just ran into this same problem when implementing ocLazyLoad and had to go through and redefine all of my controllers and such after wasting a lot of time trying to find the problem...

What's the difference between `app` and `angular.module('app')? Doesn't `angular.module('app')` just get the instance of `app`? Why does the latter work while the former doesn't?

Also, is there a way to map `app.controller` to `angular.module('app').controller` so the definitions don't have to be changed?

**Comment by ocombe** [comment]
The difference is a question of variable scopes. The variable app is not available within another file. If you define it on window.app, then it would work.
Whereas angular.module('app') is a function that will get the reference, and since angular is a global variable then it's available for you there.

**Comment by mastermoin** [comment]
as following this thread i modified my controller like : 

define(['angular', 'lodash'], function(angular, _) {
    return angular.module('myApp').controller('homeCtrl',[...]);
});

but still same problem  : Argument 'homeCtrl' is not a function, got undefined.

please give me some hint to over come with this

**Comment by mohantorrez** [comment]
I also have this same problem. app.controller works fine if i use without lazyloading. Is there any solution to use app.controller instead of angular.module?

**Comment by essivision** [comment]
+1

**Comment by burakkilic** [comment]
+1

**Comment by nirmalgoswami** [comment]
if you want to use `app.controller` instead of `angular.module('appname').controller` than you need use following code

```
App.config(['$stateProvider', '$httpProvider', '$locationProvider', '$urlRouterProvider', '$controllerProvider', '$compileProvider', '$filterProvider', '$provide', '$ocLazyLoadProvider',
    function ($stateProvider, $httpProvider, $locationProvider, $urlRouterProvider, $controllerProvider, $compileProvider, $filterProvider, $provide, $ocLazyLoadProvider) {

     
        App.controller = $controllerProvider.register;
        App.directive = $compileProvider.directive;
        App.filter = $filterProvider.register;
        App.factory = $provide.factory;
        App.service = $provide.service;
        App.constant = $provide.constant;
        App.value = $provide.value;

       
        
    }]);
```
