### ISSUE TITLE
Javascript/CSS version control to bypass browse caching

### ISSUE THREAD

**Issue by TheNightFall** [ocombe/ocLazyLoad#183]
OcLazyLoad should have a built-in way for us to define a version control for javascript and css files.
The fundamental problem this feature would solve is that the browser would stop caching js and css files when someone upgrades the server side.
A common approach to solve this issue is to add a fake "version" parameter to the request.
By studying the ocLazyLoad code I was able to detect the `cacheBuster` function that could be refactored as following:

```javascript
    cacheBuster = function cacheBuster(url, cache) {
        if(!cache){ //or === false?         
            var dc = new Date().getTime();
            if (url.indexOf("?") >= 0) {
                if (url.substring(0, url.length - 1) === "&") {
                    return "" + url + "_dc=" + dc;
                }
                return "" + url + "&_dc=" + dc;
            } else {
                return "" + url + "?_dc=" + dc;
            }
        //this version argument should be previously declared and initialized (emptied)
        }else if (version){
            return "" + url + "?_vs=" + version;  
        }
    }
```

I imagine that the version variable should be injected into the `config` property of the `ocLazyLoadProvider`.
A different approach would be to publish a callback in the `buildElement` function, this callback (when assigned) would receive the url as a parameter and return the "parsed" url:

```javascript
$ocLazyLoadProvider.config.OnPrepareUrl = function prepare(Url){
  return url + "whatever I Want";
}

```

The key advantage in this feature is that it will retain the version control for js/css files inside the lazyLoad, so developers would not need to concatenate the version on each file name.
If there is another solution for this issue please tell me, I would really appreciate.

**Comment by TheNightFall** [comment]
I will use ETags

**Comment by ocombe** [comment]
Ah I forgot to answer to you, sorry.
Glad to know that you found a better way to do it (etags are especially made for this) :)
