### ISSUE TITLE
Instantiation fails when invoke name is Object function (toString, toLocaleString,...)

### ISSUE THREAD

**Issue by martinratinaud** [ocombe/ocLazyLoad#184]
trying to register a component with a reserved name like in

```
angular.module('templates')
    .filter('toString', function () {
```
will produce the error below
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
TypeError: regInvokes[moduleName][type][invokeList].indexOf is not a function
```

To prevent this, in function `registerInvokeList`, we should use `!regInvokes[moduleName][type].hasOwnProperty(invokeList)` instead of `angular.isUndefined(regInvokes[moduleName][type][invokeList])`

I will do a PR soon.

Thanks for this awesome module

**Comment by ocombe** [comment]
Waiting for the PR, thanks :)

**Comment by martinratinaud** [comment]
Done, but very quickly, when do you plan to merge it ?

**Comment by ocombe** [comment]
Once I've had the time to test it, probably tonight

**Comment by martinratinaud** [comment]
Awesome,

although, I don't manage to run `gulp build-files`, should I ?

**Comment by ocombe** [comment]
Not really, but you can add a test if you like, it's always appreciated :)
