### ISSUE TITLE
Infinite loop with angular-google-gapi

### ISSUE THREAD

**Issue by Calzzetta** [ocombe/ocLazyLoad#186]
I am using [angular-google-gapi](https://github.com/maximepvrt/angular-google-gapi/) and when I call the command GApi.load('loginApi','v1',BASE); it start a infinite loop:
![capturar](https://cloud.githubusercontent.com/assets/6546413/7757380/370f48d0-ffd8-11e4-8a5c-8b90518bc0df.PNG)
Could that be a problem related with angular-google-gapi or ocLazyLoad?
I already started a thread there too: https://github.com/maximepvrt/angular-google-gapi/issues/14

Thank you!

**Comment by Calzzetta** [comment]
Please mark as closed. The problem was related with gapi.

**Comment by ocombe** [comment]
Ok :)
