### ISSUE TITLE
Incorrect oclazyload path in examples folder

### ISSUE THREAD

**Issue by kumarvishal** [ocombe/ocLazyLoad#187]
I was learning oclazyload(v0.6.3) with help of examples, but in ```index.html``` files path to load ocLazyLoad seems to be incorrect.

**I guess it should point to:** ``` <script src="../../dist/ocLazyLoad.js"></script>``` **Instead of** ``` <script src="../../src/ocLazyLoad.js"></script>```

**Comment by ocombe** [comment]
At the time of 0.6.3 it was probably ok to link to src since it was not written in ES6 :)
