### ISSUE TITLE
Resovle request, which was failed.

### ISSUE THREAD

**Issue by Dryymoon** [ocombe/ocLazyLoad#189]
If occurred some error in resolve request, for example - server is unrechable, ocLazyLoad return deferred.reject; 
But in future, even if server is reachable, if some module rerequest same dependencies, it will immidiately returned as rejected.

reject come from ocLazyLoad.js:803:37
@version v1.0.0-beta.2

This is a Bug or a Hint? And how I can redefine this beahiour - if the request failed,with the second same request was an attempt to resolve it.

**Comment by ocombe** [comment]
hu that's really not what is supposed to happen. I wonder if it's because the browser caches the error and returns it everytime after that ?

**Comment by Dryymoon** [comment]
>> I wonder if it's because the browser caches the error and returns it everytime after that ?
No, Browser don`t cache. I tested on several browsers, - Chrome with cache disabled, Firefox.. maby caching requests, Opera with cache disabled, MS IE not tested. I created custom function thet call $http.get request with same file, and it resolved normaly.

**Comment by ocombe** [comment]
Ok, I'll check it out then, it's probably some internal caching inside the lib then :)
If you have a working use case (code or plunkr) it would help !

**Comment by Dryymoon** [comment]
I can`t simulate this on plunkr because for investigate the problem we need to manage network or server for become unreachable.

Some code:
JS:
<code>
angular
  .module('app', ['ui.router','oc.lazyLoad']);

angular.module('app')
  .config(
    [          '$stateProvider', '$urlRouterProvider',
      function ( $stateProvider,   $urlRouterProvider ) {
        $stateProvider
            .state('sign', {
              templateUrl: 'components/login/views/login.main.html',
              }
            })
.state('sign.forgotPassword', {
              url: '^/forgot-password',
              templateUrl: 'part.forgot-password.html',
              resolve: {
                deps: ['$ocLazyLoad',
                  function( $ocLazyLoad ){
                    return 
$ocLazyLoad.load(['components/login/scripts/forgotPasswordCtrl.js']);
/* This is where a bug */
                }]
              }
            });
</code>

HTML (login.main.html):
<code>
<a ui-sref="sign.forgotPassword">Test</a>
</code>

**Comment by ocombe** [comment]
Thanks, that should do it

**Comment by ocombe** [comment]
Fixed!
It's weird that no one else ever reported this, because this bug was probably here since a really long time :)

**Comment by wuyuedefeng** [comment]
I also met the same problem, have to solve
