### ISSUE TITLE
Don't load all modules

### ISSUE THREAD

**Issue by Falci** [ocombe/ocLazyLoad#193]
**Scenario**:
I have an application so as follows:

```
angular.module('app', ['app.core', 'app.views', 'app.resources', ...]);
angular.module('app.core', ['app.core.config', ...]);
angular.module('app.resources', ['ngResource', ...]);
...
// I check a parameter to decide whether to call this module or not
angular.module('app.resources.ProductsResoucesMock', []);
```

I have a gulp task  to concatenate all JS into one.
I have divided the project into modules, each in a js file with multiple ```angular.module ()```.

In the main application I added the ocLazyLoad, to call other modules.

**The problem is**: ocLazyLoad loads the file and *starts* all angular.modules().

**Can I use ocLazyLoad to load a js file and also set which angular.module need to be called?**

**Comment by ocombe** [comment]
You might be able to load the files using:

```js
$ocLazyLoad.jsLoader(paths, callback, params);
```

And then injecting only the modules that you need:

```js
$ocLazyLoad.inject(moduleNames, params);
```

I haven't tried that but it might work :)
`inject` returns a promise, and jsLoader uses a callback (it wasn't supposed to be called directly).

**Comment by Falci** [comment]
It works!

```
      var params = {};

      $ocLazyLoad.jsLoader(['moduleA.js', 'moduleB.js'], function(){
        $ocLazyLoad.inject(['moduleA.core', 'moduleB.core'], params);
      }, params);
```

Thanks!

**Comment by ocombe** [comment]
Perfect :)

**Comment by teja422** [comment]
@Falci Can I get any sample code for the reference

**Comment by Falci** [comment]
I'm sorry, probably not anymore.
