### ISSUE TITLE
Support for angular 1.4

### ISSUE THREAD

**Issue by kschwidder** [ocombe/ocLazyLoad#195]
Could you please provide support for 1.4 as it is out now and major libs are providing support for it.

**Comment by ocombe** [comment]
Well it's supposed to work, isn't it ?

**Comment by kschwidder** [comment]
Bower.json is not supporting 1.4.0. Please update bower file instead. Can than test it

**Comment by ocombe** [comment]
Well it does:
``` "angular": ">=1.2.x <=1.4.x" ```

Check it here: http://semver.npmjs.com/

**Comment by kschwidder** [comment]
This is what I get from bower install:
Unable to find a suitable version for angular, please choose one:
    1) angular#>=1.2.x <=1.4.x which resolved to 1.3.16 and is required by oclazyload#1.0.1

**Comment by ocombe** [comment]
Did you clean your bower cache ? `bower cache clean`
Also, maybe you have another bower module that is defined as 1.3.x and since ocLazyLoad is also compatible with this version it will take it?
And finally if that doesn't help you can add angular 1.4 as a dependency for your project and bower will select it since you manually defined it.

**Comment by kschwidder** [comment]
I did the last one :-)
Your module is awesome !!! It works like a charm.

**Comment by ocombe** [comment]
Good. I'll take a look at this when I have the time, because it should be working with this expression.

**Comment by soq-pierre** [comment]
Same issue for me.
All my dependencies are resolved to angular 1.4.3 except ocLazyLoad who said:
> 1) angular#>=1.2.x <=1.4.x which resolved to 1.3.17 and is required by oclazyload#1.0.4

In my bower.json I have this line : 
```json
    "angular": "~1.4.3",
```
and 
```json
    "oclazyload": "~1.0.4",
```

I executed the ```bower cache clean``` command but no effect.

Thanks for your help!

**Comment by ocombe** [comment]
Well that's weird, because the semver expression is valid, bower may not follow the npm syntax properly... ?
I could probably change it to >=1.2.x, I'll do it in the next version

**Comment by soq-pierre** [comment]
OK !
Thanks for your prompt reply :wink:

**Comment by estaub** [comment]
Re-reporting same problem.  I'd suggest that using 'x' in comparisons, as in "<=1.4.x", is unusual, at the very least.  A brief search found no example of use or specification of how it would be interpreted, including at https://github.com/npm/node-semver .  I'm a noob, though!  If anyone needs a quick fix, e.g., for heroku deployment, add a "resolutions" section (a peer to "dependencies") to force what you need, e.g.:
```
  "resolutions": {
    "angular": "1.4.3"
  },
```

**Comment by Ideaktif** [comment]
Please support angular 1.4

**Comment by sargin48** [comment]
Please support angular 1.4
i cant install ocLazyLoad

**Comment by ocombe** [comment]
Yes I'll be back from my holidays tomorrow, I'll do it this week end. Sorry
for the inconvenience.

Le jeu. 20 août 2015 17:00, Abdullah SARGIN <notifications@github.com> a
écrit :

**Comment by sargin48** [comment]
Thanks ocombe.

**Comment by ocombe** [comment]
Ok I changed it to >=1.2.0, let me know if it works (once I released a new version)
