### ISSUE TITLE
[$injector:modulerr] Failed to instantiate module oc.lazyLoad due to: [$injector:nomod] Module   ‘undefined’ is not availablele 

### ISSUE THREAD

**Issue by chenxingjun** [ocombe/ocLazyLoad#200]
When I open browser Internet Explorer 7 (7.0.5730)
Status tools appear error:
[$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
[$injector:nomod] Module   ‘undefined’ is not available!

But chrome (43.0.2357) is great.Console not appear error.

**Comment by ocombe** [comment]
Not enough details to work with here... Closing. I'll reopen if you have more details to provide but I'm not a magician, I cannot debug by sheer will...
