### ISSUE TITLE
Update on NPM

### ISSUE THREAD

**Issue by jvandyke** [ocombe/ocLazyLoad#202]
Latest version on bower: 1.0.1 
Latest version on npm: 0.6.3 from 2015-03-09

Can we get a bump? :smile:

**Comment by ocombe** [comment]
oh woops, I though it was automatic on my release process but not for that lib it seems (I did setup that for another of my libs).
Thanks for the reminder, I'll do it right now

**Comment by ocombe** [comment]
Done, thanks !

**Comment by jvandyke** [comment]
You're the best. Thanks!

James
