### ISSUE TITLE
ocLazyLoad compatibility IE8?

### ISSUE THREAD

**Issue by chenxingjun** [ocombe/ocLazyLoad#204]
ocLazyLoad compatibility IE8?

**Comment by ocombe** [comment]
yes

**Comment by chenxingjun** [comment]
网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; KB974489)
时间戳: Fri, 26 Jun 2015 08:49:17 UTC


消息: [$injector:modulerr] Failed to instantiate module ckeApp due to:
[$injector:modulerr] Failed to instantiate module ckeApp.framework.system due to:
[$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
[$injector:nomod] Module 'undefined' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=undefined
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=oc.lazyLoad&p1=%5B%24injector%3Anomod%5D%20Module%20'undefined'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fnomod%3Fp0%3Dundefined
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=ckeApp.framework.system&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20oc.lazyLoad%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'undefined'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fnomod%3Fp0%3Dundefined%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fmodulerr%3Fp0%3Doc.lazyLoad%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'undefined'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.28%252F%2524injector%252Fnomod%253Fp0%253Dundefined
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=ckeApp&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ckeApp.framework.system%20due%20to%3A%0A%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20oc.lazyLoad%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'undefined'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fnomod%3Fp0%3Dundefined%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fmodulerr%3Fp0%3Doc.lazyLoad%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'undefined'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.28%252F%2524injector%252Fnomod%253Fp0%253Dundefined%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fmodulerr%3Fp0%3DckeApp.framework.system%26p1%3D%255B%2524injector%253Amodulerr%255D%2520Failed%2520to%2520instantiate%2520module%2520oc.lazyLoad%2520due%2520to%253A%250A%255B%2524injector%253Anomod%255D%2520Module%2520'undefined'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.28%252F%2524injector%252Fnomod%253Fp0%253Dundefined%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.28%252F%2524injector%252Fmodulerr%253Fp0%253Doc.lazyLoad%2526p1%253D%25255B%252524injector%25253Anomod%25255D%252520Module%252520'undefined'%252520is%252520not%252520available!%252520You%252520either%252520misspelled%252520the%252520module%252520name%252520or%252520forgot%252520to%252520load%252520it.%252520If%252520registering%252520a%252520module%252520ensure%252520that%252520you%252520specify%252520the%252520dependencies%252520as%252520the%252520second%252520argument.%25250Ahttp%25253A%25252F%25252Ferrors.angularjs.org%25252F1.2.28%25252F%252524injector%25252Fnomod%25253Fp0%25253Dundefined
行: 3893
字符: 7
代码: 0
URI: http://192.168.0.100:8080/bower_components/angular/angular.js

**Comment by chenxingjun** [comment]
OK,I know it reason now.

angular.module('ckeApp.framework.system', [
	
	'ui.router',
	'ui.bootstrap',
	'oc.lazyLoad',
])

need delete comma  <b>,<b>
