### ISSUE TITLE
How use with Datatables, Web Api (Async call) ?

### ISSUE THREAD

**Issue by Kris-I** [ocombe/ocLazyLoad#207]
Hello,

I'd like use Datatable. I use AngularJS 1.4.1 and the datas coming from an Web Api service with $http call (promise). The grid is generated with data but has a strange, lose data when sorting.

Do you think ocLazyLoad can help me ? I checked the samples and ... Im' not sure.

Thanks,

**Comment by ocombe** [comment]
What do you need ocLazyLoad for? Lazy loading the lib datatable ?

**Comment by Kris-I** [comment]
Keep in mind I'm not a front end guys :)

I use a theme from Themeforest called "Metronic". They use datatables. I can feed the datatable, I see the datatable with data, but the behavior is strange when I sort the columns datas disappear, I get the message "No data available in table" but there are data. I call the support and they told my they use ocLazyLoad to load JS and CSS.... it's why I'm here.

I suppose, I have to get data before create the datatable.

I have a sample online here http://metronictesting.azurewebsites.net/ click "Login" and then customer > search 

Thanks  for your fast answer.

**Comment by ocombe** [comment]
Hmm I don't think that this has anything to do with ocLazyLoad.
As they said, this lib is used to load the js/css files, but once that's done (and it works since your datatable exists), it doesn't load data for the libs.
If datatable is unable to load new data on sort, I'm guessing that it has to do with your server config or something ?

**Comment by Kris-I** [comment]
When I do a sort, there is no call to the web api. I don't know what I can do there is no call then ...  :(

**Comment by ocombe** [comment]
Well I don't know, but if you have some support with them, they should be the ones checking it out :)
I don't think it has anything to do with this lib anyway.

**Comment by ocombe** [comment]
Closing for now, reopen it if you need.
