### ISSUE TITLE
How to load directive in ui-router using $ocLazyLoad

### ISSUE THREAD

**Issue by lrondanini** [ocombe/ocLazyLoad#208]
Hi all,

I've seen similar questions but no solution seems to work for me.

I'm trying to lazy load directives in ui-router. The idea is that the template would be something like "&lt;my-directive&gt;&lt;/my-directive&gt;" and I'm using resolve to load the JS for the directive.

Looking around and reading the documentation this is what I got so far.

    app.config(function($stateProvider, $urlRouterProvider) {
         $urlRouterProvider.otherwise("/");

     var lazyDeferred = {};

     $stateProvider.state('app',{
        url: '/app/:id/:directive',
        templateProvider: function() { return lazyDeferred.promise; },
        resolve: {
            load: ['$ocLazyLoad','$q','$http','$stateParams','$compile', function($ocLazyLoad, $q, $http,$stateParams,$compile) {
                lazyDeferred = $q.defer();
                return $ocLazyLoad.load('/directives/calculator.js').then(function() {
                    var template = "<"+$stateParams.directive+"></"+$stateParams.directive+">";
                    return lazyDeferred.resolve(template);
                });

            }]
        }

    });
    });

The JS is loaded correctly and the directive's tag is correctly added to ng-view but I cannot see any result. I tried to use compile but it's not working either.

Any idea? Thanks

**Comment by lrondanini** [comment]
I've found a solution. 

1. config your app as:

app.config(function($compileProvider)  {
	app.compileProvider = $compileProvider;
});

2.  define your directive as 
 app.compileProvider.directive('directiveName',........)


I'm not very happy with this because I didn't see anyone mentioning this solution! Any comment?

**Comment by ocombe** [comment]
This should work I think:

```js
app.config(function($stateProvider, $urlRouterProvider) {
     $urlRouterProvider.otherwise("/");

      var lazyDeferred = {};

      $stateProvider.state('app',{
         url: '/app/:id/:directive',
         templateProvider: function() { return lazyDeferred.promise; },
         resolve: {
             load: ['$ocLazyLoad','$q','$http','$stateParams','$compile','$rootScope', function($ocLazyLoad, $q, $http,$stateParams,$compile,$rootScope) {
                 lazyDeferred = $q.defer();
                 return $ocLazyLoad.load('/directives/calculator.js').then(function() {
                     var template = $compile(angular.element("<"+$stateParams.directive+"></"+$stateParams.directive+">"))($rootScope);
                     return lazyDeferred.resolve(template);
                 });
             }]
         }
     });
});
```

**Comment by lrondanini** [comment]
Thanks man but it requires too many "tricks" to make it work. Your solution returns an HTML element object that the templateProvider doesn't know how to handle. Not a big deal, totally fixable but at this point seems more "clean" to add the new directive directly to the $compileProvider.

Thanks a lot for your help! I have to admit that I didn't think about compiling using the $rootScope. My fault, I'm so used to stay away from it as much as possible to not mess up my code too much that i always forget about it!
