### ISSUE TITLE
Directive not being triggered after compiling

### ISSUE THREAD

**Issue by serraventura** [ocombe/ocLazyLoad#211]
Directive not being triggered after compiling. I can see the directive compiled on my DOM but the template is not being loaded. If I hardcode the module (not lazy way) the template works fine.

Is there anything I could be missing?

Main module:

```javascript
'use strict';

angular.module('App', [
	'oc.lazyLoad',
	'ui.bootstrap',
])

.config(['$ocLazyLoadProvider', function($ocLazyLoadProvider){

	$ocLazyLoadProvider.config({
		modules: [
			{
				name: 'FinderMod',
				files: [
		            'src/finder/module.js',
		            'src/finder/controllers/finder.js',
		        	'src/finder/directives/finder.js',
		        	'src/finder/services/finder.js'
				]
			}
		]
	});

}])
```

Directive which load the lazy module
```javascript
'use strict';

angular.module('App')
	.directive('widget', function($ocLazyLoad, $rootScope, $compile){
		return {
			restrict:'A',
			priority: 0,
			replace: false,
			controller: function($scope) {

			},
			link: function(scope, element, attrs) {

				var lazyModule;
				var directiveTemplate = '';
				var scope = $rootScope.$new();

				switch ( (attrs.widgetname||'').toLowerCase() ) {

					case 'finder':

						lazyModule = 'FinderMod';
			            directiveTemplate = '<div finder ></div>'

						break;
					default: 
						// text = "";
				};

	            $ocLazyLoad.load(lazyModule).then(function () {

	                var elToAppend = $compile(directiveTemplate)(scope);
	                element.append(elToAppend);

	            }, function (e) {
	                console.log(e);
	            });


			}
		}
	})
```

Directive which should be compiled
```javascript
'use strict';

angular.module('FinderMod')
	.directive('finder', function(){
		return {
			restrict:'A',
			controller: 'FinderCtrl',
			template: '<span>should load this template</span>',
			link: function(scope, element, attrs) {
			}
		}
	})
```

**Comment by ocombe** [comment]
I think the correct syntax for $compile is:
```js
var elToAppend = $compile(angular.element(directiveTemplate))(scope);
element.append(elToAppend);
```

You're missing the `angular.element` part.

**Comment by serraventura** [comment]
I've tried in this way but keep the same issue. Could be the angular version?
My angular version is 1.2.28. 

* oclazyload - Load modules on demand (lazy load) with angularJS
 * @version v1.0.1

**Comment by ocombe** [comment]
Oh that's an old version of angular. It might be the cause, I usually test on 1.3 (and now 1.4)... It should work on 1.2 but maybe there's a bug somewhere.
Could you make me a plunkr so that I can take a closer look at your code ?

**Comment by serraventura** [comment]
Could not replicate so far. Both working fine.

Not lazy load: http://plnkr.co/edit/6OfPgOxFtovZjXWuhUhv?p=preview
lazy load: http://plnkr.co/edit/a7CLVRUA3eLCla0HKPjR?p=preview

**Comment by serraventura** [comment]
Could be an issue bootstrap the app by hand? Because that's what I'm doing on my app.

**Comment by ocombe** [comment]
Since you're loading the module definition in a separate file, you have to make sure that it is loaded before the controller & the service. You can use the parameter `serie` for that, and it works: http://plnkr.co/edit/Pnjv5MimlHjEsd5aXRe3?p=preview:
```js
.config(['$ocLazyLoadProvider', function($ocLazyLoadProvider){

    $ocLazyLoadProvider.config({
        modules: [
            {
                name: 'FinderMod',
                files: [
                    'module.js',
                    'finder1.js',
                    'finder2.js'
                ],
                serie: true
            }
        ]
    });
}])
```
