### ISSUE TITLE
Bower search result pointing to incorrect github URL

### ISSUE THREAD

**Issue by paullang** [ocombe/ocLazyLoad#212]
When I searched bower for your package  http://bower.io/search/?q=oclazyload
it only comes up with a link to LazyHelper https://github.com/niceilm/LazyHelper which is 5 days old

bower install oclazyload installs the correct package though.

**Comment by ocombe** [comment]
Well both my lib and lazyhelper are listed on bower, and lazyhelper seems to be an helper for ocLazyLoad, so I don't see any harm in this ?

**Comment by paullang** [comment]
Interesting. Now yours is listed in the search results too, but this morning it wasn't.

![oclazyload](https://cloud.githubusercontent.com/assets/1221447/8640059/e261b5b6-289f-11e5-8897-a10a270e7d8b.PNG)

Sounds like the bower registry search isn't very robust.

**Comment by ocombe** [comment]
Well, it happens :) Thanks for the report though
