### ISSUE TITLE
Controller not found while using UI-Router

### ISSUE THREAD

**Issue by thedarklord1** [ocombe/ocLazyLoad#216]
I am using angular-1.3.15, UI-Router-0.2.15 and ocLazyLoad-1.0.2 (Latest checked out from Git). While trying to lazy load a controller, It gives me error that the controller does not exist, while if I insert a timeout in resolve, it works perfectly. Could you give me any leads, as to what I might be doing wrong. 

First one without timeout:
```javascript
$stateProvider.state('app.resume', {
            url: '/resume',
            templateUrl: 'partials/jobs/resume.html',
            controller : 'ResumeController',
            resolve :{
                lazyload_jobs :['$ocLazyLoad', function($ocLazyLoad){
                    $ocLazyLoad.load('lazyload/jobs_resumecontroller.js');
                }]
            }
        })
```

ScreenShot:

![screen shot 2015-07-23 at 1 32 26 pm](https://cloud.githubusercontent.com/assets/8191081/8846085/00e13f34-3142-11e5-8c16-69ccf7fa64b2.png)

With timeout:

```javascript
$stateProvider.state('app.resume', {
            url: '/resume',
            templateUrl: 'partials/jobs/resume.html',
            controller : 'ResumeController',
            resolve :{
                lazyload_jobs :['$ocLazyLoad', function($ocLazyLoad){
                    $ocLazyLoad.load('lazyload/jobs_resumecontroller.js');
                }],
                delay : ['$timeout', function($timeout){
                    return $timeout(function(){console.log("after 50 mil");},100);
                }]
            }
        })
```

ScreenShot:

![screen shot 2015-07-23 at 1 41 59 pm](https://cloud.githubusercontent.com/assets/8191081/8846150/52af09e0-3142-11e5-814e-4a4dfad227de.png)

My Controller code is really big, and it performs some network requests also. Should I be worried about this fact? Any lead is appreciated. 

TIA.

**Comment by ocombe** [comment]
Hmm, the controller shouldn't be executed until requested, so I don't think it's the problem... You try with an empty controller and see what happens?
If you don't have the problem then there's something fishy here.
If you still have the problem then it's something else.

**Comment by thedarklord1** [comment]
Thanks for such quick reply @ocombe :)
And yes, it is working with empty controller. I guess I must be doing some kind of sin or something in my controller. For the starters, I am going to resolve all my network requests before entering in the controller and see if that helps. 
Thanks a lot.

**Comment by ocombe** [comment]
That's really weird.
What happens here is that ocLazyLoad loads the file, and once it's injected in the dom it calls the controller provider and tells him to add the newly loaded controller, then it resolves, but it looks like the execution of the provider takes longer than the resolve, which is really weird because the resolve is promise based and should be executed at the end of the digest cycle... and the execution of the provider should be synchronous.

If you find out what the problem is, I'd be interested in knowing the cause.

**Comment by thedarklord1** [comment]
I think it might be re-created by injecting some time delay in the controller execution. I will try to re-create this on plunker and share it with you.

**Comment by ocombe** [comment]
That'd be great, thanks!

**Comment by thedarklord1** [comment]
Yeah, it is not working if there is some delay in Controller. Create your controller like this, and it will stop working.

```javascript
angular.module('resumecontrollerapp',[]).controller('ResumeController',
    ['$scope', '$rootScope', function ($scope, $rootScope) {
        console.log("I am in ResumeController start");
        function pausecomp(millis)
        {
            var date = new Date();
            var curDate = null;
            do { curDate = new Date(); }
            while(curDate-date < millis);
        }
        pausecomp(1000);
        console.log(" ResumeController finished ");
    }]);
```

To double check if it is the same time out issue, I inserted a delay of 2 seconds in my resolve, and it worked.

**Comment by ocombe** [comment]
Hmm but I don't get it, the controller function should only be executed when linked to the dom and then it shouldn't throw an error of undefined...
I wonder if it has to do with the way ui router loads the controller, let me summon higher powers here: @christopherthielen

**Comment by christopherthielen** [comment]
I'd be happy to look at a plunkr.  Do you think you can make that happen @thedarklord1?

**Comment by thedarklord1** [comment]
Sure @christopherthielen . I will do it ASAP.

**Comment by thedarklord1** [comment]
Here is the plunkr : http://plnkr.co/edit/1ye1jG0KmTN31a8jaBIZ?p=preview

But there is a catch. It runs some of the times, and fail to run some times. You need to run it for like a couple of times to recreate the error. I must have been doing some thing really stupid here. Please go gentle on me if you find that. I am attaching the screenshot for your reference. 

![screen shot 2015-07-24 at 1 38 06 pm](https://cloud.githubusercontent.com/assets/8191081/8870217/bc7b6ea0-3209-11e5-80bf-799b158446e3.png)

**Comment by christopherthielen** [comment]
@thedarklord1 in the case of your plunkr, you're not returning the promise in the resolve

```
            resolve :{
                lazyload_jobs :['$ocLazyLoad', function($ocLazyLoad){
                    return $ocLazyLoad.load('myController.js'); // <------- HERE
                }]
            }
```

**Comment by ocombe** [comment]
Damn it you're right, I missed this :)
Looks like a good reason for the race condition ;)

**Comment by christopherthielen** [comment]
It's so easy to overlook

**Comment by thedarklord1** [comment]
I see it. 
Thanks a lot for doing this. :)
