### ISSUE TITLE
.run() doesn't invokes for lazyloaded modules in 1.0.3 after fix for .config() invoking. 

### ISSUE THREAD

**Issue by captify-ddavydov** [ocombe/ocLazyLoad#218]
// I'm lazy-loaded module
angular.module('myModule', ['ngTable'])
.config(function() {
        alert('I'm invoked');
    })
    .run(function() {
        alert('Can't invoke( ');
    })

**Comment by ocombe** [comment]
probable duplicate of https://github.com/ocombe/ocLazyLoad/issues/217

**Comment by ocombe** [comment]
Fixed in 1.0.4, thanks for the report !

**Comment by captify-ddavydov** [comment]
Now it works! Thank a lot!
