### ISSUE TITLE
Using route parameters in resolve?

### ISSUE THREAD

**Issue by oneHappyCanuck** [ocombe/ocLazyLoad#219]
Apologies if this is a silly question but I'm new to ocLazyLoad.

Wondering if its possible to access route parameters within the resolve method?  I'd like to dynamically select the files to be loaded based on the actual route.

**Comment by oneHappyCanuck** [comment]
Found a similar question here 
http://stackoverflow.com/questions/13433116/routeparams-doesnt-work-in-resolve-function

Seems to work :) 

   resolve: {
            lazy: ['$ocLazyLoad','$route', function($ocLazyLoad,$route) {
              return $ocLazyLoad.load({
                name: $route.current.params.type+'Ctrl', 
                files: ['app/scripts/controllers/'+$route.current.params.type+'.js']
              });
            }]
        }

**Comment by ocombe** [comment]
Yup that's how you'd do it !
Closing the issue :)
