### ISSUE TITLE
How can to lazyload in before run

### ISSUE THREAD

**Issue by mouryaamit** [ocombe/ocLazyLoad#220]
Hi,
    I have some dependencies which need to be loaded for run method. But I am not getting hoe to achieve it

```
app.run(["myDep", function(myDep){
});
```

I need to lazy load the myDep

**Comment by ocombe** [comment]
could you do something like that ?
```js
app.run(["$ocLazyLoad", "$injector", function($ocLazyLoad, $injector){
  $ocLazyLoad.load('myDep').then(function() {
    var myDep= $injector.get('myDep');
    // do something with myDep
  }, function(err) {
    console.error(err);
  });
});
```

**Comment by mouryaamit** [comment]
And if I need to load multiple dependencies, How can I do. I tried with array but then it gives error

**Comment by ocombe** [comment]
You'll need to call $injector multiple times, once for each dependency.
$injector is a service from Angular, not for $ocLazyLoad :)
