### ISSUE TITLE
Lazy load directive using module name ("inject") instead of javascript file

### ISSUE THREAD

**Issue by angular-tools** [ocombe/ocLazyLoad#223]
Hi,

Please look at this plunkr below:

http://plnkr.co/edit/Mhno7w?p=preview

In `one.html` I'm trying to `inject` the module by name (instead of .js file) but it is **not** working.

In `two.html` when I `load` it using the javascript file path it works!

How can I make `one.html` work (i.e. where the javascript file is already loaded but the module needs to be loaded by name)?

**Comment by angular-tools** [comment]
Hi,

This seems to fix it:

In `ocLazyLoad.directive.js`:

    if (angular.isDefined(moduleName)) {
       $ocLazyLoad[angular.module(moduleName) ? 'inject' : 'load'](moduleName).then(function () {


Does this look appropriate?

**Comment by ocombe** [comment]
The dom of one.html is parsed by angular before `$scope.lazyLoadParams` is available (since you define `$scope.lazyLoadParams` in this same partial).
Either define it somewhere else, or you need to call `$compile` again to make it work.
