### ISSUE TITLE
Misleading docs - oclazyload with Systemjs not working (maybe just a bug?)

### ISSUE THREAD

**Issue by kresli** [ocombe/ocLazyLoad#224]
Hi,
According to the docs  https://oclazyload.readme.io/docs/systemjs, Systemjs should works without any issues already but it looks like oclazyload is not loading new modules into angular structure. There is no error in console so Im not sure what happening. I created this repo as an example https://github.com/kresli/systemjs-oclazyload-seed-example. Even I can see that the modules went through the oclazyload, the run function in third module is not evaluated.
After cloned repo please run this commands:
```npm install```
```./node_modules/jspm/jspm.js install```
``` ./node_modules/serve/bin/serve ```

**Comment by kresli** [comment]
Looks like this is issue with oclazyload version. As @scottmcnab  described here https://github.com/ocombe/ocLazyLoad/issues/221, degrading oclazyload to lower version from 1.0.4 to 1.0.3 cause config successfully initialised but run is still not invoked. However, degrading oclazyload to 1.0.1 version, everything works ok.

**Comment by Mosho1** [comment]
Same here, reverting to 1.0.1 works for me as well. However, this might not be related to SystemJS, see #221

**Comment by ocombe** [comment]
Yes it's related to #221, closing this one as it is in fact a duplicate. Thanks for the report though
