### ISSUE TITLE
How do modules in ocLazyLoad loaded, parallel or in sequence?

### ISSUE THREAD

**Issue by anatoly314** [ocombe/ocLazyLoad#226]
I'd like to duplicate [my question from stackoverflow][3] here too...

I'm using [ocLazyLoad][1] library to achieve lazy loading for all dependencies in my project. I know that by default files are loaded in parallel and to make it loaded in sequence I should use `serie:true` https://github.com/ocombe/ocLazyLoad/issues/47

From [this thread][2] I understand that I can load modules in series:

> Yes the files are loaded in parallel, if you want to multiple modules
> at the same time and that they require one another you either need to
> define them in different object params:
```js
    $ocLazyLoad.load([{
        name: 'TestModule',
        files: ['testModule.js', 'testModuleCtrl.js', 'testModuleService.js']
    },{
        name: 'AnotherModule',
        files: ['anotherModule.js']
    }]);
```

Now I try to load all dependencies required for FullCalendar in my application, there's my ocLazyLoad config file:
```js
    $ocLazyLoadProvider.config({
    		 debug: true,
    		 modules: [{
    			    name: 'ngCkeditor',
    			    files: [
    			            	'resources/bower_components/ng-ckeditor/libs/ckeditor/ckeditor.js',
    			            	'resources/bower_components/ng-ckeditor/ng-ckeditor.min.js',
    			            	'resources/bower_components/ng-ckeditor/ng-ckeditor.css'
    			            ],
    			    serie: true
    		 },{
    			    name: 'ui.calendar',
    			    files: [
    			            'resources/bower_components/fullcalendar/dist/fullcalendar.min.js',
    			            'resources/bower_components/fullcalendar/dist/lang/he.js',
    			            'resources/bower_components/fullcalendar/dist/gcal.js',
    			            'resources/bower_components/angular-ui-calendar/src/calendar.js',
    			            'resources/bower_components/fullcalendar/dist/fullcalendar.min.css'
    			            ],
    			    serie: true
    		 },{
    			    name: 'ngFileUpload',
    			    files: [
    			            	'resources/bower_components/ng-file-upload/ng-file-upload.min.js'
    			            ]
    		 },{
    			    name: 'momentjs',
    			    files: [
    			            	'resources/bower_components/moment/min/moment.min.js'
    			            ]
    		 }]
    	});
```
And this is part of my router:
```js
    .state('schedule',{
    			url: '/schedule',
    			controller:		'ScheduleController',
    			templateUrl:	'schedule.html',
    			resolve: {
    		          loginRequired: loginRequired,
    		          loadMyCtrl: ['$ocLazyLoad', function($ocLazyLoad) {
    		              // you can lazy load files for an existing module
    		                     return $ocLazyLoad.load(['momentjs','ui.calendar','ngCkeditor']);
    		           }]
    		    }
    		})
```
Despite that module `'momentjs'` defined at first place I still get an error: `Uncaught ReferenceError: moment is not defined`

If I put `moment.js` in `'ui.calendar'` module it works, but I'd like to load it separately because I have another views in my application where I use only moment.js and doesn't need all dependencies. 

So, my question is, how to make moduls (not files) to be loaded in a serie, not files or if they already loaded in a serie, what can cause to my mistake?

Thank you in advance.

  [1]: https://oclazyload.readme.io/
  [2]: https://github.com/ocombe/ocLazyLoad/issues/34
[3]:http://stackoverflow.com/questions/32274048/how-do-modules-in-oclazyload-loaded-parallel-or-in-sequence

**Comment by ocombe** [comment]
Hey, sorry for the late answer.
The API has changed a bit since the issue that you linked.
If you put `serie: true` in the module definition, it will only load the files of this module in serie. If you have multiple modules that you want to load in serie (because they depend on each other), you need to use the param serie globally like this:

```js
    $ocLazyLoadProvider.config({
             debug: true,
             serie: true
             modules: [{
                    name: 'ngCkeditor',
                    files: [
                                'resources/bower_components/ng-ckeditor/libs/ckeditor/ckeditor.js',
                                'resources/bower_components/ng-ckeditor/ng-ckeditor.min.js',
                                'resources/bower_components/ng-ckeditor/ng-ckeditor.css'
                            ],
                    serie: true
             },{
                    name: 'ui.calendar',
                    files: [
                            'resources/bower_components/fullcalendar/dist/fullcalendar.min.js',
                            'resources/bower_components/fullcalendar/dist/lang/he.js',
                            'resources/bower_components/fullcalendar/dist/gcal.js',
                            'resources/bower_components/angular-ui-calendar/src/calendar.js',
                            'resources/bower_components/fullcalendar/dist/fullcalendar.min.css'
                            ],
                    serie: true
             },{
                    name: 'ngFileUpload',
                    files: [
                                'resources/bower_components/ng-file-upload/ng-file-upload.min.js'
                            ]
             },{
                    name: 'momentjs',
                    files: [
                                'resources/bower_components/moment/min/moment.min.js'
                            ]
             }]
        });
```

See the `serie: true` that I added at the start (outside the modules definition).

**Comment by anatoly314** [comment]
@ocombe, thank you very much!

**Comment by m98** [comment]
I am doing it, but I don't know why do I get this error:

> TypeError: Cannot read property 'shift' of undefined

**Comment by offwork** [comment]
I don't understand why I can't install the dependencies mentioned in the related files in place?

`(function() {
    "use strict";

    angular
        .module('app.core', [
        'blocks.exception',
            {
                files: [
                    '/app/blocks/exception/exception.module.js',
                    '/app/blocks/exception/exception.js',
                    '/app/blocks/exception/exception-handler.provider.js'
                ],
                cache: false
            },
        'blocks.logger',
            {
                files: [
                    '/app/blocks/logger/logger.module.js',
                    '/app/blocks/logger/logger.js'
                ],
                cache: false
            },
        'blocks.router',
            {
                files: [
                    '/app/blocks/router/router.module.js',
                    '/app/blocks/router/router-helper.provider.js'
                ],
                cache: false
            },
        'ngSanitize',
        'ngMaterial',
        'md.data.table',
        'ngMask',
        'ui.router',
        'oc.lazyLoad']);
})();`

**Comment by IbrahimHd** [comment]
Did you try to include module name inside the `name `property? like this:

```
angular
    .module('app.core', [
        {
            name:'blocks.exception',
            files: [
                '/app/blocks/exception/exception.module.js',
                '/app/blocks/exception/exception.js',
                '/app/blocks/exception/exception-handler.provider.js'
            ],
            cache: false
        },
.....
```

**Comment by offwork** [comment]
Yes I tried but, the problem is these modules cannot be loaded before from dependencies, I think.

**Comment by DevFacts** [comment]
I have two angular module 
1. app module
2. testModule 
so, i wanted to load the testModule later on while it needed 
therefore configure like the following  way 

in main app config file.
$ocLazyLoadProvider.config({
                debug: true,
                events: true,
                reconfig:true,
                cache: false,
                modules: [
                    {
                        name: 'testModule',
                        files: ["testModule.js"]
                    }
                ]
            });

testModule.js 


class TestService  {
    static $inject = ["$uibModal"];
    show() {
        this.$uibModal.open({
            template:"<h1>Hello modal</h1>",
            animation: true
        })
    }
}


angular.module("testModule",[])
    .service("testService", TestService);

If it is use not, it works well 

But now, 

as i wanted to load testModule file using $oclazyload 

my app.js file controller

openModal(){
let self = this;
        this.$ocLazyLoad.load("testMudule").then(() => {
            let modal = self.$injector.get("testService");
            modal.show();
        });
}

file gets loaded while i trigger the function. But service does't get and trigger the show function . 

where i have done mistake. please help anyone.
I like to say thanks in advance for solve.

**Comment by prakulgupta** [comment]
> Hey, sorry for the late answer.
> The API has changed a bit since the issue that you linked.
> If you put `serie: true` in the module definition, it will only load the files of this module in serie. If you have multiple modules that you want to load in serie (because they depend on each other), you need to use the param serie globally like this:
> 
> ```js
>     $ocLazyLoadProvider.config({
>              debug: true,
>              serie: true
>              modules: [{
>                     name: 'ngCkeditor',
>                     files: [
>                                 'resources/bower_components/ng-ckeditor/libs/ckeditor/ckeditor.js',
>                                 'resources/bower_components/ng-ckeditor/ng-ckeditor.min.js',
>                                 'resources/bower_components/ng-ckeditor/ng-ckeditor.css'
>                             ],
>                     serie: true
>              },{
>                     name: 'ui.calendar',
>                     files: [
>                             'resources/bower_components/fullcalendar/dist/fullcalendar.min.js',
>                             'resources/bower_components/fullcalendar/dist/lang/he.js',
>                             'resources/bower_components/fullcalendar/dist/gcal.js',
>                             'resources/bower_components/angular-ui-calendar/src/calendar.js',
>                             'resources/bower_components/fullcalendar/dist/fullcalendar.min.css'
>                             ],
>                     serie: true
>              },{
>                     name: 'ngFileUpload',
>                     files: [
>                                 'resources/bower_components/ng-file-upload/ng-file-upload.min.js'
>                             ]
>              },{
>                     name: 'momentjs',
>                     files: [
>                                 'resources/bower_components/moment/min/moment.min.js'
>                             ]
>              }]
>         });
> ```
> 
> See the `serie: true` that I added at the start (outside the modules definition).

In the latest version 1.1.0, on setting serie globally doesn't downloads bundles sequentially. If I have bundle1 with files {f1,f2,f3} and bundle2 with files{f4,f5}. Then expected sequence of files should be f1,f2,f3,f4,f5. But actual outcome is different like f1,f4,f2,f3,f5 or f1,f4,f2,f5,f3,
Also I looked into the code. No where we have used global serie which we pass in config. So how the bundles will be downloaded in sequence?
Please let me know in which version this was working?
