### ISSUE TITLE
The `signature` function can be really slow

### ISSUE THREAD

**Issue by phenomnomnominal** [ocombe/ocLazyLoad#228]
I have a case where I do an initial AJAX request for quite a large set of data (~10000 items), which is registered as an `angular.constant` before bootstrap occurs. When ocLazyLoad runs and calls the `signature` function on this data it hangs for a good few seconds while it stringifies the whole thing. Any suggestions for getting around this?

**Comment by ocombe** [comment]
Hmm, that can be a problem yes.
You could try to optimize the function and do a PR? Or maybe we could change the code to add a custom "id" that you give me to identify the code (and not use the signature in this case)?

**Comment by phenomnomnominal** [comment]
Had a go at a [PR](https://github.com/ocombe/ocLazyLoad/pull/229), I think it makes sense?

**Comment by ocombe** [comment]
Perfect thanks !

**Comment by phenomnomnominal** [comment]
This is out so I'll close the issue :)
