### ISSUE TITLE
Replacement Controller not getting reloaded

### ISSUE THREAD

**Issue by micmur** [ocombe/ocLazyLoad#235]
I need to load html and controller based on data on the parent record. 

I am replacing the same controller each time I load the edit page, so the parent controller can just be set to call that controller name and it will always be the latest code that goes along with the child form.

I have 3 child html pages. Each one calls oc-lazy-load to load a controller that has the same name.

When I first call child 1, everything works. I call child 2, still everything works. However, when I call child 1 again, it doesn't replace the code that child 2 loaded and therefore fails. I've tried adding cache: false, reconfig: true, rerun: true. It still doesn't work. (you'll see that on animalsCtrl.js under $ocLazyLoadProvider.config)

In the console, the ocLazyLoad.fileLoaded and ocLazyLoad.moduleReloaded run again, but the ocLazyLoad.componentLoaded does not.

I've created an example: http://plnkr.co/edit/xQvYQv?p=preview

If you click on the edit on the dog, you'll see the status go to "edit dog" (comes from the new loaded controller) and the fields are loaded on the detail tab. Click Save or Cancel

If you click on the edit on a cat, you'll see the status go to "edit cat" (newly loaded controller) and the fields are loaded on the detail tab. Click Save or Cancel

Now if you go back to the dog, the status will say "edit cat". It's not reloading the controller code for the dog.

**Comment by ocombe** [comment]
Yes it is impossible to replace an angular component that has already been instantiated because Angular will keep it in memory.
The solution in your case would be to give different names to each pet controller (DogEditController, CatEditController, ...).
I updated your plunkr with a working draft: http://plnkr.co/edit/irytskzh3ksFYnaCS2CO?p=preview

**Comment by micmur** [comment]
OK, thank you. I was originally doing that, but I wanted to use the same name so the parent controller didn't have to know what type of child it was to save.

I think my real issue is that I still have some learning to do in the Angular side.

Thank you for your help. That was fast!

**Comment by ocombe** [comment]
No problem, glad I could help!

**Comment by dgreene1** [comment]
For future visitors, I believe it's safe to say that the controller based approach to angular is now considered a code smell. Component based development appears to work much better with libraries like UI-Router and ocLazyLoad. In other words: I believe that the workaround for this github issue is to just not use controllers at all. Use a ".component" or a directive with isolate scope instead. 

@ocombe Please advise me if I am correct: You can still replace a directive or a ".component" with a new one with the same name, right?

More information on preferring component over controller:
https://juristr.com/blog/2016/06/from-ngcontroller-to-components/
