### ISSUE TITLE
SystemJS based load does not work as expected

### ISSUE THREAD

**Issue by bronzovik** [ocombe/ocLazyLoad#237]
SystemJS load (the first example from docs: https://oclazyload.readme.io/docs/systemjs) does not work with $ocLazyLoad.load(), but works with $ocLazyLoad.inject(). Control breaks out of the loop in _register when module object is passed to load().

I'm not sure if this is intended behaviour. Anyway, this should be reconciled with docs.

**Comment by ocombe** [comment]
Thanks for the report, I'll check that out :)

**Comment by bronzovik** [comment]
Np. modules[moduleName] comes up as true to be more specific. Thanks!
