### ISSUE TITLE
Provide some events when loading files? 

### ISSUE THREAD

**Issue by xggaxlc** [ocombe/ocLazyLoad#243]
I want to show loading image when data loading,so I use HTTP Interceptors,but ocLazyLoad can not play well with it. if add some events when loading files well nice.forgive my poor english.

**Comment by ocombe** [comment]
the loaders from ocLazyLoad don't use http (except for templates), that's why you don't get anything in your interceptors. But since they use promises, you can start the loading animation before you call the load function and end it after the promise has resolved.

**Comment by xggaxlc** [comment]
Thank you ! It works fine!

**Comment by ocombe** [comment]
:+1:

**Comment by moravcik** [comment]
I have the same problem as @xggaxlc, but I would like to make it more generic. I know there is `ocLazyLoad.fileLoaded` event which I could use to detect when file loading is finished. What I am missing is an event when a file is requested to load, e.g. `ocLazyLoad.fileLoad` so I could cover all usages of `$ocLazyLoad.load(...)`
