### ISSUE TITLE
Initial load when app initialize

### ISSUE THREAD

**Issue by Jeevanandanj** [ocombe/ocLazyLoad#247]
When I give routing, this will try to match all the routing url and will come back to the login page as per my application.

In my case I need to load some initial file for authentication reason and to initialize my app.
So Initially I need to load only ocLazyload, angularjs and jquery.

The remaining parts should be loaded when I initialize the app. How to achieve this?

**Comment by ocombe** [comment]
You can add a resolve to the route of the page that requires the files that you're lazy loading.
Otherwise if you need to lazy load this for all the routes, you can put it in the .run of your main module.
