### ISSUE TITLE
Why there is only "fileLoaded", but no "moduleLoaded", when using $ocLazyLoad.load('example.js') 

### ISSUE THREAD

**Issue by yssource** [ocombe/ocLazyLoad#251]
Using $ocLazyLoad.load, is only loading my js file.
But, the defined module is not loaded and the module is undefined.
If I using the requirejs only instead of ocLazyLoad, everything is OK.

**Comment by yssource** [comment]
my futureState.module name is 'testModule'
I have already used the $ocLazyLoadProvider.config correctly.

a.js file
defined(['angular'], function(angular){ angular.module('testModule', []);});

test.js file
$ocLazyLoad.load(futureState.module).then(function() {
      // success
      console.log('success');
      console.log('checking module: ' + futureState.module);
 }, function(err) {
      console.error(err);
 });

As a result, log will output 'success'. But, my module is undefined.

**Comment by yssource** [comment]
It seems $ocLazyLoad.load does not work with js file that defined by requirejs.
For instance, 
a.js file
If my a.js file looks like this, the module will be correctly loaded.
angular.module('testModule', []);

If it looks like this, wouldn't work.
define(['angular'], function(angular){ angular.module('testModule', []);});

So, it's possible to integrate requirejs with ocLazyLoad working together?

**Comment by ocombe** [comment]
Hello, did you use the file "ocLazyLoad.require.js" and not " ocLazyLoad.js" from the dist folder?

**Comment by yssource** [comment]
Yes, it is solved.
You save me a lot of time.
Thanks so much for your help @ocombe .

**Comment by ocombe** [comment]
No problem :)
