### ISSUE TITLE
Infinite recursion when passing an array into `$ocLazyLoad.inject()`

### ISSUE THREAD

**Issue by danthareja** [ocombe/ocLazyLoad#252]
I'm using ocLazyLoad with webpack and ran into an overflowing call stack when calling `$ocLazyLoad.inject()` on an array. 

It looks like #242 made this change to solve another issue. Is there some fix that can handle both cases?

Code snippet of my implementation for reference:

```js
require.ensure([], function(require) {

  // Require our modules
  // This replaces the `import` statements from above
  let something = require('./about.something'); // an angular module
  let component = require('./about.component'); // Just a directive factory function

  // Inject all dependencies into our module
  // This replaces adding them to the original angular.module dependency array
  $ocLazyLoad.inject([
    something.name
  ])

  // Register the component so the template recognizes it
  .then(() => $compileProvider.directive('about', component))

  // Continue the state transition
  .then(deferred.resolve);

}, 'about'); // Name our bundle so it shows up pretty in the network tab
```

**Comment by tepez** [comment]
Also have this issue moved back to 1.0.5

The error is causes by this [line](https://github.com/ocombe/ocLazyLoad/commit/953584e8989de7ed1c2166ca193c899bad8a3478#diff-1fd73cf111b732007013adf123e0ac21R598).
