### ISSUE TITLE
How to pack files of “$ocLazyLoad.load” ？

### ISSUE THREAD

**Issue by harole** [ocombe/ocLazyLoad#254]
![image](https://cloud.githubusercontent.com/assets/4095799/10449280/1d41ba50-71c5-11e5-8481-385d87c89b4e.png)

Just like the picture, we need to pack all files to three departments ( sdk.js, component.js, modules.js).

I have no idea about the problem. Anyone help me? 

Thanks!

**Comment by ocombe** [comment]
Well, if you want to bundle your files, you have to do it in your dev process, that's no something that ocLazyLoad will help you with :)
