### ISSUE TITLE
Require JS double callback trigger error

### ISSUE THREAD

**Issue by weblucaseduardo** [ocombe/ocLazyLoad#266]
ocLazyLoad.require.js line 1198

Because of this change, when I run $ocLazyLoad.load("app/module"),

and my module.js exports a value, ocLazyload thinks that it was an error
how can I change it?

**Comment by ocombe** [comment]
Hey, did you close the issue on purpose ?

**Comment by weblucaseduardo** [comment]
I found the problem, I needed to create my own jsLoader, calling the callback without parameters,
something like this
$ocLazyLoad.jsLoader = function(paths, callback, params) {
				require(paths, function() {
					callback();
				}, callback);
};
$ocLazyLoad.jsLoader.requirejs = true;

because the module I want to load will return something, and the default callback consider that as an error.
