### ISSUE TITLE
After loading, how to access loaded module and inject it to main module in run section?

### ISSUE THREAD

**Issue by mirkhamidov** [ocombe/ocLazyLoad#270]
I got a code

```
(function(){
    angular
        .module('MyApp')
        .run(_run);

    _run.$inject = ["$rootScope", "settings", "$ocLazyLoad"];

    function _run($rootScope, settings, $ocLazyLoad)
    {

        // START loading
        $ocLazyLoad.load('UserModule').then(function(d){
            console.log(d);
            console.log(user);
        });
        // END loading

        // INIT or define some data
        $rootScope.$settings  = settings;
    }
})();
```

but after `UserModule` loaded
there is no `user` factory
What am I doing wrong?

conten of `UserModule.js`

```
;(function(){
    angular.module('UserModule', []);

    (function(){
        angular.module('UserModule')
            .factory('user', _user);

        function _user()
        {
            var user = {
                info : {},
                isAuth : getIsAuth,
                setAttr : setAttr
            };
            
            return user;

            ///////////

            /**
             * @return {boolean}
             */
            function getIsAuth()
            {
                return false;
            }

            /**
             * @param {string}
             * @param {mixed}
             * @return {boolean}
             */
            function setAttr(attr, val)
            {
                user[attr] = val;
            }
        }
    })();
})();
```

how `UserModule` defined:
```
(function(){
    angular
        .module('crmApp')
        .config(['$ocLazyLoadProvider', _ocLazyLoadProvider]);

    function _ocLazyLoadProvider($ocLazyLoadProvider)
    {
        $ocLazyLoadProvider.config({
            // global configs go here
            debug: true
            , modules : [
                {
                    name : 'UserModule',
                    // cache : false,
                    reconfig : false,
                    rerun : false,
                    insertBefore : '#ng_load_plugins_before',
                    files : [
                        '/app/modules/user/module.js'
                    ]
                }
            ]
        });
    }
})();
```

**Comment by ocombe** [comment]
You write `console.log(user);` but where do you define this variable ?
If you want to use the loaded UserModule in the "then" function, you need to use the injector. For example (from the FAQ):

```js
var app = angular.module("myApp", ["oc.lazyLoad"]);

app.controller('MyCtrl', function($scope, $ocLazyLoad, $injector) {
    $ocLazyLoad.load('ngDialog.js').then(function() {
        var ngDialog = $injector.get('ngDialog');
        ngDialog.open({
            template: 'dialogTemplate'
        });
    });
});
```

**Comment by mirkhamidov** [comment]
@ocombe sorry, I added some code ))
I need to inject to a main module in run section

**Comment by ocombe** [comment]
Then you should probably ask user to the injector:

```js
var user = $injector.get('user');
```

**Comment by mirkhamidov** [comment]
@ocombe nice, it works.
But, what if there will be more than one service/directives/factories?
Is it possible to inject whole loaded `UserModule` module to main application module?

**Comment by ocombe** [comment]
You can inject them in a new controller for example, but any existing (and loaded) component will have to use the injector.

The best use case for $ocLazyLoad is to use it in the resolve of a route, and then use the loaded component in this route (use a loaded controller, or use the loaded services in the controller, or use the loaded directives in the view used by this route).

In your case, since the run function is already loaded (and has been injected), if you want something that you loaded you need to use the $injector yourself.

**Comment by mirkhamidov** [comment]
hm....
But what is a best solution, to dynamic load `UserModule` (mainly it is a factory, which works with user data and authorization via API) to the main `app`?

**Comment by ocombe** [comment]
well if you load it into the "run" of your main module, then it means that you need it for your application. In which case you should not lazy load it, but you should just load it as usual with your webpage

**Comment by mirkhamidov** [comment]
pity...
I thought,that I can load dynamicly some global modules too

**Comment by ocombe** [comment]
you can, but what the point if you need it before your application can start ?
If that's not the case then put the load in the resolve of one of your routes

**Comment by mirkhamidov** [comment]
ok, thanks
