### ISSUE TITLE
Hope this would be helpful

### ISSUE THREAD

**Issue by jack4it** [ocombe/ocLazyLoad#274]
Hi, I have a lazy loading demo project setup using various technologies including ocLazyLoad, systemjs, ui-router, etc. I'm wondering maybe you can put up a link to [the post](http://jackma.com/2015/12/30/a-lazy-loading-solution-for-angular-1-x/) and [GitHub repo](https://github.com/jack4it/angular-1x-lazy-load) on your external links page here https://oclazyload.readme.io/docs/external-help-articles-tutorials-videos. So that folks can leverage the solution I have which is fresh and fully functional.

Thanks,
-Jack

**Comment by ocombe** [comment]
Sure no problem !
