### ISSUE TITLE
Location.path not working in services/factories for lazyloaded modules.

### ISSUE THREAD

**Issue by sanyam-j** [ocombe/ocLazyLoad#275]
$location is not working in factory services loaded later using lazyroute in ui router.

**Comment by ocombe** [comment]
How is it not working ? An error in the console ?

**Comment by sanyam-j** [comment]
No error. Its work properly when for modules loaded on page load. But as i load more modules in ui router and inject them to root module. It doesn't work in newly added factories. I have using it http resolve. Is returns the promise but not change the location if http get failed.

LazyLoad.factory("DetailService", ['$q', '$http', '$location',
  function($q, $http, $location){
    return {
      getDetail: function (slug) {
        var deferred = $q.defer();

        $http.get(apiPath + "/hotel/" + slug + "/")
          .then(function(response){
            deferred.resolve();
          }, function(error) {
            $location.path("/");
            deferred.reject(error);
          });
        return deferred.promise;
      }
    }
  }
]);

**Comment by ocombe** [comment]
And you're positive that the failed request executes your error callback?
If you load the same module without ocLazyLoad it works?

**Comment by sanyam-j** [comment]
Yes its work fine without lazyload. While looking into the issue, i found a more exact situation for it. Its not working inside $http request. If i place $location & reject it before the http request. It works fine.

**Comment by sanyam-j** [comment]
Hi, I think i found the issue. Its not with lazyload. Its when we use ui router and location service, then location service doesn't work inside http request. Earlier i was using route provider, so its working for me at that time. As i had changed it to ui router and lazyload, what i am thinking is that its not working bz of lazyload. But its the issue for angular ui router.

**Comment by ocombe** [comment]
ok, that makes more sense.
You're supposed to use `$state.go` with ui router
