### ISSUE TITLE
Error: [ng:areq] Argument 'HomePageController' is not a function, got undefined

### ISSUE THREAD

**Issue by udaysurendra** [ocombe/ocLazyLoad#281]
Hi there,
**Error: [ng:areq] Argument 'HomePageController' is not a function, got undefined**
I am getting this error when i am loading my  HomePageController with  ocLazyLoad. But while loading file  directly into page it is working fine .

Here below i made a plnkr with my problem please look into this.

[Open Code In plnkr](https://plnkr.co/edit/OfGzmT?p=preview)

**Comment by ocombe** [comment]
Hello,

just change `assocAdmin` to `angular.module('assocAdmin')` in your lazy loaded controller, because `assocAdmin` is a global variable that isn't available in the lazy loaded context :-)

**Comment by brutalcrozt** [comment]
@udaysurendra  you may read this [question](http://stackoverflow.com/questions/21673404/error-ngareq-from-angular-controller "ng:areq")
