### ISSUE TITLE
ocLazyLoad + Angular 1.5 + Angular 2 + ngUpgrade = sad day

### ISSUE THREAD

**Issue by amcdnl** [ocombe/ocLazyLoad#288]
With the following stack:
- ocLazyLoad
- Angular 1.5
- Angular 2
- ngUpgrade

when I drop in ngUpgrade it dies with the following:

```
angular.js:70 Uncaught Error: [$injector:modulerr] Failed to instantiate module NG2_UPGRADE_0_ due to:
Error: [$injector:modulerr] Failed to instantiate module swimlane due to:
Error: [$injector:modulerr] Failed to instantiate module core due to:
Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
No module found during bootstrap, unable to init ocLazyLoad
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=oc.lazyLoad&p1=No%20module%20found%20during%20bootstrap%2C%20unable%20to%20init%20ocLazyLoad
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:70:12
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4528:15
    at forEach (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:323:20)
    at loadModules (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4489:5)
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4506:40
    at forEach (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:323:20)
    at loadModules (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4489:5)
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4506:40
    at forEach (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:323:20)
```

from my convo with @ocombe:

> yeah, there's a bug with the fact that I override angular.module and ng upgrade does the same. no idea, but it should be possible to make it work, I don't see why not the unit test angular mock package override angular.module as well and I made it work. https://github.com/ocombe/ocLazyLoad/blob/master/src/ocLazyLoad.core.js#L728-L732 I think that "return ngModuleFct(name, requires, configFn);" (L731) is probably different with ng upgrade or maybe angular.bootstrap is different.

**Comment by amcdnl** [comment]
If you declare oc first it will work! see:

```
import angular from 'angular';
import 'ocLazyLoad';
import { adapter } from './adapter';
```

**Comment by amcdnl** [comment]
Actually now my app runs but I have an issue with components that are lazy-loaded.

```
export default angular
  .module('vsualization', [ core.name ])
  .config(ConfigureModule)
  .directive('vizPage', adapter.downgradeNg2Component(VizComponent));
```

gives me the following:

```
angular.js:13238 Error: Expecting HostViewFactoryRef for: vizPage
    at directiveFactory (http://10.211.55.5:9000/jspm_packages/npm/angular2@2.0.0-beta.7/src/upgrade/upgrade_adapter.js:134:13)
    at Object.invoke (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4606:19)
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:7477:43
    at forEach (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:323:20)
    at Object.<anonymous> (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:7475:13)
    at Object.invoke (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4606:19)
    at Object.enforcedReturnValue [as $get] (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4445:37)
    at Object.invoke (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4606:19)
    at http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4405:37
    at Object.getService [as get] (http://10.211.55.5:9000/jspm_packages/npm/angular@1.5.0/angular.js:4552:39) undefined
```

Which someone actually mentions on Angular Github Issue - https://github.com/angular/angular/issues/7027 and its due to the fact that: "downgrading the component after you've already bootstrapped".

**Comment by amcdnl** [comment]
So haven't had time to hack at it much but i think i know the issue.  Essentially both ng-upgrade and ocLazyLoad override the `angular.module` type stuff. Therefore they are getting out of order.

Essentially you want ...
- ocLazy to load first and register the module
- ngUpgrade to run on that ( might need to do something crazy like their router does for ng2 stuff )
- normal angular.module code to run

**Comment by amcdnl** [comment]
@ocombe Odd .. actually its not this project causing the issues ... i made a simple demo here and it works.... - https://github.com/amcdnl/angular2-upgrading

**Comment by ocombe** [comment]
:o that's good news, but maybe it doesn't work with everything ?

**Comment by amcdnl** [comment]
Ya, i wonder if its future state or something :S ...

**Comment by amcdnl** [comment]
actually dumby me, i did a ng1 component :o

**Comment by duncangrist** [comment]
@amcdnl - thanks for the example, I'll see whether I can get it to work with our app using those principles.

**Comment by duncangrist** [comment]
I've spent a little more time looking at this today, and I've managed to get it to work :)

Essentially, if you're registering a downgraded ng2 component after bootstrap time, you also have to ensure that you invoke `compileNg2Components()` on the upgrade adapter before you try to use it.

e.g. if you're using ocLazyLoad to load a new ui-router state, lazily (using ui-router-extras "future states" for example) then you could do something like:

	// ng1/pages/lazy.js

	import {upgradeAdapter} from 'ng2/upgrade-adapter.ts';
	import {LazyComponent} from 'ng2/pages/lazy/lazycomponent.ts';

	angular.module('app.lazy', ['ui.router'])

		.config($stateProvider => {
			$stateProvider.state('lazy', {
				url: '/lazy',
				views: {
					"main": {
						template: require('./lazy.tpl.html')
					}
				},
				resolve: {
					ng2: ['ng2.Compiler', 'ng2.HostViewFactoryRefMap', (compiler, hostViewFactoryRefMap) => {
						return upgradeAdapter.compileNg2Components(compiler, hostViewFactoryRefMap);
					}]
				}
			});
		})

		.directive('lazyComponent', upgradeAdapter.downgradeNg2Component(LazyComponent));

**Comment by amcdnl** [comment]
@duncangrist Nice, was actually on my list today! 

PR my repo so we can see a full working example and then @ocombe can give us some feedback and even add to docs?

**Comment by amcdnl** [comment]
@duncangrist - WORKS! Thanks for helping!

@ocombe heres my setup and is working:

```
import angular from 'angular';
import futureRoutes from 'app/routes.json!';
import 'ui-router-extras-future';
import { adapter } from 'app/adapter';

export default function(module){
  module.requires.push('ct.ui.router.extras.future');
  
  let RouterConfig = ['$stateProvider', '$futureStateProvider', function ($stateProvider, $futureStateProvider) {
    $futureStateProvider.stateFactory('load', ['$q', '$ocLazyLoad', 'futureState', 'cfpLoadingBar', 'ng2.Compiler', 'ng2.HostViewFactoryRefMap',
      function($q, $ocLazyLoad, futureState, cfpLoadingBar, compiler, hostViewFactoryRefMap){

      let def = $q.defer();

      System.import(futureState.src).then(function(loaded){
        let newModule = loaded;
        if(!loaded.name){
          newModule = loaded.default;
        }
        
        adapter.compileNg2Components(compiler, hostViewFactoryRefMap);

        $ocLazyLoad.load(newModule).then(function(){
          def.resolve();
        }, function(err) {
          throw err;
        });
      });

      return def.promise;
    }]);

    futureRoutes.forEach(function(r){
      $futureStateProvider.futureState(r);
    });
  }];
  
  return RouterConfig;
};
```

**Comment by ocombe** [comment]
:+1: thanks for the hard work you two

**Comment by brandonroberts** [comment]
Nice! Do you have to use this with future states? Have you run into any issues using any upgraded ng1 component with this method?

**Comment by amcdnl** [comment]
@brandonroberts No, thats just how I use oc, you can do it like @duncangrist did above.

**Comment by brandonroberts** [comment]
@amcdnl I see. Thanks!

**Comment by amcdnl** [comment]
@duncangrist FYI, Angular2 Beta16 breaks our solution. 

Error I get:

```
jspm_packages/npm/angular@1.5.2/angular.js:13294 Error: [$injector:unpr] Unknown provider: ng2.HostViewFactoryRefMapProvider <- ng2.HostViewFactoryRefMap
http://errors.angularjs.org/1.5.2/$injector/unpr?p0=ng2.HostViewFactoryRefMapProvider%20%3C-%20ng2.HostViewFactoryRefMap
    at eval (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:68:12)
    at eval (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4418:19)
    at Object.getService [as get] (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4571:39)
    at eval (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4423:45)
    at getService (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4571:39)
    at injectionArgs (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4595:58)
    at Object.invoke (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:4617:18)
    at eval (http://localhost:8080/jspm_packages/github/Swimlane/ui-router-extras@master/release/modular/ct-ui-router-extras.future.js:151:40)
    at processQueue (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:15627:28)
    at eval (http://localhost:8080/jspm_packages/npm/angular@1.5.2/angular.js:15643:27) undefined(anonymous function) @ jspm_packages/npm/angular@1.5.2/angular.js:13294
http://localhost:8080/signalr/negotiate?clientProtocol=1.5&auth_token=eyJhb…ctionData=%5B%7B%22name%22%3A%22modelnotification%22%7D%5D&_=1461673549790 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by ocombe** [comment]
damn :(

**Comment by amcdnl** [comment]
Update: `HostViewFactoryRefMap` was renamed to `ComponentFactoryRefMap`

**Comment by amcdnl** [comment]
FYI - This is broken in RC5

**Comment by amcdnl** [comment]
With the drop of Angular 2.0.1, the issues with ui-router and ng1-to-ng2 adapter have been resolved. I'm working on hooking all this up in a demo project here: https://github.com/swimlane/ng1-ng2-webpack-lazy-uirouter

Would love to hear if anyone has this going already.
