### ISSUE TITLE
May i load assets serially ?

### ISSUE THREAD

**Issue by gordomium** [ocombe/ocLazyLoad#297]
As a directive:

```jade
div oc-lazy-load="assetUrls"
```

It works parallel like:

```js
$ocLazyLoad.load(assetUrls)
```

May i load assets serially without `CMD` / `AMD` / `...` like: 

```jade
div oc-lazy-load-sync="assetUrls"
```

Works as:

```js
$ocLazyLoad.load.apply($ocLazyLoad, assetUrls)
```

====

```js
assetUrls = [
  baseAsset,
  anAssetRequiresBaseAsset,
  ...
]
```

I can't use the common module loaders like `requirejs` or `seajs` ... in some section

**Comment by ocombe** [comment]
You can use the param `serie: true` to load in serie.
With a directive it would be:
```hml
<div oc-lazy-load="{serie: true, files: assetUrls}"></div>
```
