### ISSUE TITLE
Is there any plan to support angular2?

### ISSUE THREAD

**Issue by hstarorg** [ocombe/ocLazyLoad#331]

**Comment by ocombe** [comment]
You don't need ocLazyLoad for angular 2, it's built in because it's using ES6 modules. The router for example supports lazy loading, but they are working on a new way to lazy load (so if you're not in a hurry, you should wait a few weeks).

**Comment by hstarorg** [comment]
Thank you very much.
In my project, a folder is a module, a module include some components and services(develop by other team), it will be build as a js file. I want to dynamic load this js file, would you give me some idea?(Sorry, my English is a little poor, I hope you can understand.)

**Comment by ocombe** [comment]
In an angular 1 or angular 2 project?
Are you using systemjs or webpack?

**Comment by hstarorg** [comment]
Angular2 project, used webpack.

**Comment by ocombe** [comment]
You can check this: https://github.com/angular/angular/issues/9375

**Comment by hstarorg** [comment]
Thank you, I also used 'ui-router-ng2'. I will try this angular/angular#9375.

**Comment by hstarorg** [comment]
``require.ensure`` required a known component. In my project, components developed by other teams. 
When redirect to '/module1/xxx', I will use 'module1' as the module name and load all components in module1.

**Comment by hstarorg** [comment]
My project structure demo: https://github.com/hstarorg/HstarDemoProject/tree/master/angular_demo/angular-lazyload-demo
