### ISSUE TITLE
Two js files in a module, one js file should be loaded before the other one

### ISSUE THREAD

**Issue by youyouttok** [ocombe/ocLazyLoad#339]
Hello, angular-chart depend on Chart.js , but Chart.js could not be loaded before angular-chart.js.

```
app.constant("Modules_Config", [{
    name: "ui.chart",
    module: true,
    files: [
      "../js/swan/chart/Chart.js", "../js/swan/chart/angular-chart.js"
    ]
  }])
  .config(["$ocLazyLoadProvider", "Modules_Config", routeFn]);

function routeFn($ocLazyLoadProvider, Modules_Config) {
  $ocLazyLoadProvider.config({
    debug: false,
    events: false,
    modules: Modules_Config
  });
};
```

```
.state("mainPage", {
    url: "/mainPage",
    views: {
      "": {
        templateUrl: "mainPage.html"
      }
    },
    resolve: {
      deps: ["$ocLazyLoad", function($ocLazyLoad) {
        return $ocLazyLoad.load([
          'ui.chart',
          '../js/controller/chartController.js'
        ]);
      }]
    }
  })
```

![image](https://cloud.githubusercontent.com/assets/19164114/17960028/66fba178-6ad6-11e6-9a27-577f3b770037.png)

**Comment by youyouttok** [comment]
![image](https://cloud.githubusercontent.com/assets/19164114/17959779/15e038c2-6ad5-11e6-962c-ac4187f69333.png)

**Comment by ohjames** [comment]
@youyouttok You could search for the first module's existence in an $interval and then load the next one. That's how I've done it. Can give you the code if you need it.

**Comment by ocombe** [comment]
or you could use the parameter `serie: true` so that it loads your files in serie

**Comment by ohjames** [comment]
Shouldn't that be `series`?

**Comment by ocombe** [comment]
From the docs:
```
$ocLazyLoad.load({
  serie: true,
  files: [
    'bower_components/angular-strap/dist/angular-strap.js',
    'bower_components/angular-strap/dist/angular-strap.tpl.js'
  ]
});
```

**Comment by ohjames** [comment]
There is no word `serie` in the English language, I believe you intended to use `series`.

**Comment by ohjames** [comment]
Although `serial` would probably be a more appropriate term here.

**Comment by ocombe** [comment]
Sure.

**Comment by youyouttok** [comment]
@ocombe 
Thank you!I used serie in module config, and in route like this:
```
resolve: {
			loadModule: ["$ocLazyLoad", function($ocLazyLoad) {
		    	console.log(1);
		        return $ocLazyLoad.load(['ui.chart']);
		    }],
		    loadMyCtrl: ['$ocLazyLoad', 'loadModule', function($ocLazyLoad, loadModule) {
		    	console.log(2);
		        return $ocLazyLoad.load({
		            files: ['../js/controller/chartController.js']
		        });
		    }]
		}
```
it works!

**Comment by youyouttok** [comment]
@ohjames Thank you! I have used serie to solve the problem. I will try to use your solution to do it.

**Comment by ohjames** [comment]
My solution was not good, it's much better to use `serie`, you can compose the promise it returns for more advanced dependency trees.
