### ISSUE TITLE
How to dependency injection using ocLazyLoad

### ISSUE THREAD

**Issue by m98** [ocombe/ocLazyLoad#353]
This question asked on [Stackoverflow ](http://stackoverflow.com/questions/39875533/how-to-dependency-injection-using-oclazyload) but no one answered that, I was curious to know the answer, and I posted that here:

I'm using ocLazyLoad and I have some external angular libraries (Like Chart.js and pascalprecht.translate) and I need to lazy load them in some routes, as you know, for the common angular module dependency injection should be like:

```
var angularApp = angular.module('myApp',
     ['oc.lazyLoad', 'pascalprecht.translate', 'chart.js']);
```

Now, I just need to lazy loading pascalprecht.translate in one of my controllers and also lazy loading chart.js, in another controller, but I still need to add inject them to myApp module but I don't know how to inject and I do not use $stateProvider

**I tried this my controller that I needed chart.js:**
```
//Load here.
//$ocLazyLoad.load('./panel/dist/test.js');
angular.module('myApp', ['chart.js', [
 './panel/dist/static/chart.min.js',
 './panel/dist/static/angular-chart.min.js'
]]);

$ocLazyLoad.load('./panel/dist/static/chart.min.js');
$ocLazyLoad.load('./panel/dist/static/angular-chart.min.js');
```

**But I got this error:**

> angular-chart.min.js:10Uncaught Error: Chart.js library needs to included, see http://jtblin.github.io/angular-chart.js/

**Comment by alo** [comment]
Hi! 
In your module definition you don't have to inject "chart.js"
```javascript
angular.module('myApp', [ 'ui.router', 'oc.lazyLoad' ]);
```
If you are using ui.router:
```javascript
angular.module('myApp').config(
    ['$stateProvider', '$urlRouterProvider',
    function ($stateProvider, $urlRouterProvider) {
      $urlRouterProvider.otherwise('/access/signin');
      $stateProvider
        .state('chart', {
          url: '/chart-view',
          templateUrl: 'path/to/your/view',
          resolve: {
            store: function ($ocLazyLoad) {
              return $ocLazyLoad.load(
                {
                  serie: true,
                  name: "chart.js",
                  files: [
                    "path/to/Chart.min.js",
                    "path/to/anguar-chart.min.js",
                  ]
                }
              );
            }
          }
        });
      }
    ]
  );
```

**Comment by m98** [comment]
Thanks 👍 

I also think, you should post the answer on Stackoverflow too, maybe people need it.

+ What if I'm not using `ui.router`? Is there any other way? 🤔

**Comment by m98** [comment]
@alo Do you know, How can I use it just by ng-route? (Without using **ui-router**)

**Comment by alo** [comment]
cool! so you can close the issue!

**Comment by ignivaravinderrikhi** [comment]
It actually works .... Hey can you explain me how it is injecting dependency ... TIA ...
