### ISSUE TITLE
Cannot get it working with TextAngular

### ISSUE THREAD

**Issue by alvarolb** [ocombe/ocLazyLoad#373]
I have tested almost everything related about this topic on the Internet during the last 2 days, but I cannot get the textAngular working with latests versions of ocLazyLoad. My setup was working fine until I updated to version 1.0.9. The last version that seems to work fine is the 0.5.2, but it miss some features I need now. 

The page stuck in white, as the dependency where not resolved. No errors on the console. I have tried loading the files in different orders, adding different files, removing minified versions, loading them in serie, but no luck!

Anyone knows if there is something special to do? Thanks

**Comment by alvarolb** [comment]
After further investigating, and enabling the lazy load load debug, I found the problem, and it is related with the textAngular Library: Unknown provider: taRegisterToolProvider <- taRegisterTool

**Comment by ocombe** [comment]
Yes, they have a circular dependency inside their lib, I reported this problem to them with the fix to do like 2 years ago, but apparently they never fixed it

**Comment by alvarolb** [comment]
Yes... I noticed it when I enabled the ocLazyLoad debug. I was working with it disabled and it was being a nightmare :) For others with this issue... this is my configuration that actually works with the latest version of both libraries:

Load order:
```
{
            name: 'textAngular',
            files: [
                'libs/angular/textAngular/dist/textAngular-rangy.min.js',
                'libs/angular/textAngular/dist/textAngular.min.js',
                'libs/angular/textAngular/dist/textAngularSetup.js',
                'libs/angular/textAngular/dist/textAngular.css'
            ],
            serie: true
        }
```

And modify `textAngularSegup.js`:

Change 

`angular.module('textAngularSetup', [])`

With

`angular.module('textAngularSetup', ['textAngular.DOM'])`

And also I have required to disable the forceTextAngularSanitize

`forceTextAngularSanitize: false` 

Hope it helps! I lost several hours with this...
