### ISSUE TITLE
Angular 1.6 compatibility

### ISSUE THREAD

**Issue by niharikasah** [ocombe/ocLazyLoad#377]
The issue is with templates loader function. The success and error callback is removed with angular 1.6. Rather it has then() and catch(). 

$http.get(url, params).success(function (data) {
                        if (angular.isString(data) && data.length > 0) {
                            angular.forEach(angular.element(data), function (node) {
                                if (node.nodeName === 'SCRIPT' && node.type === 'text/ng-template') {
                                    $templateCache.put(node.id, node.innerHTML);
                                }
                            });
                        }
                        if (angular.isUndefined(filesCache.get(url))) {
                            filesCache.put(url, true);
                        }
                        deferred.resolve();
                    }).error(function (err) {
                        deferred.reject(new Error('Unable to load template file "' + url + '": ' + err));
                    });

**Comment by alexan** [comment]
created a pull request for this 
https://github.com/ocombe/ocLazyLoad/pull/380
