### ISSUE TITLE
How to load dependences for module in proper order

### ISSUE THREAD

**Issue by nonameplum** [ocombe/ocLazyLoad#4]
Hi,

I'm learning Angular so please do not punish me :)
I wonder how to load properly service that module is using.

e.g.

```
$stateProvider
    .state(
    'somestate',
    {
        url: "/", // root route
        views: {
            "adminView": {
                templateUrl: '/view1.html'
            }
        },
        resolve: {
            test: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.load({
                    name: 'view1',
                    files: [
                        "assets/service.js",
                        "assets/module1.js"
                    ]
                });
            }]
        }
    });
```

For now module is not see service becouse of async javascript file loading.

**Comment by alexpacer** [comment]
Hi guys, I'm not sure if i'm doing it right, for this following example

    $ocProvider.config({
      modules: [
        {
          name: 'SelectBoxIt',
          files: [
            'jquery-ui/jquery-ui.min.js',
            'jquery/jquery.selectBoxIt.min.css',
            'jquery/jquery.selectBoxIt.js']
        }
      ],
      asyncLoader: $script
    });

Doesn't seems that **jquery.selectBoxIt.js** will wait for **jquery-ui.min.js** to finish loading. 

What happen to me is that they are loading in order, but **jquery.selectBoxIt.js** is calling jquery-ui **$.widget** right after its loaded, while jquery-ui is still loading. 

I'm currently doing this:


    $ocProvider.config({
      modules: [
        {
          name: 'SelectBoxIt',
          files: [
            'jquery/jquery.selectBoxIt.min.css',
            'jquery/jquery.selectBoxIt.js']
        }, 
        {
          name: 'JqueryUI',
          files: ['jquery-ui/jquery-ui.min.js']
        }
      ],
      asyncLoader: $script
    });

    $ocLazyLoad.load('JqueryUI').then(function() {
        $ocLazyLoad.load('SelectBoxIt').then(function(){
             // done..
        });
    });


But is there a better way for it to wait until previous libary finished loading?

Thanks a lot!

**Comment by ocombe** [comment]
Hello,

is there any reason why you're using $script instead of the loaders included into $ocLazyLoad ?
These loaders can use the param "serie: true" to load the files in the order that you want.

Here is how I would do it:

```js
$ocProvider.config({
  modules: [
    {
      name: 'SelectBoxIt',
      files: [
        'jquery/jquery.selectBoxIt.min.css',
        'jquery/jquery.selectBoxIt.js']
    }, 
    {
      name: 'JqueryUI',
      files: ['jquery-ui/jquery-ui.min.js']
    }
  ]
});

$ocLazyLoad.load(['JqueryUI', 'SelectBoxIt'], {serie: true}).then(function() {
     // done..
});
```

**Comment by alexpacer** [comment]
Hello @ocombe ,

Wow, this is just the feature that I was looking for! Tried it and it worked perfectly! 

I was just following the documentation and trying with different asyncLoader. But I did not know the {serie: true}'s there for the job! 

Many thanks @ocombe, I love this module :)

**Comment by ocombe** [comment]
Perfect, I'm glad you enjoy it! :)
