### ISSUE TITLE
oc-lazy-load directive does not display template

### ISSUE THREAD

**Issue by jerv13** [ocombe/ocLazyLoad#45]
This could be an issue with usage, but i cannot seem to find a good example.

When I use the directive like this the controller will work, but the directive (my-ee) will not.

    <div oc-lazy-load="{name: 'e', files: ['/modules/rcm-js-lib/TEMP/e.js']}">
        <div ng-controller="e">CONTROLLER {{modele}}</div>
        <div data-my-ee>
            DIRECTIVE DEFAULT
            <input type="text" ng-model="modele"><button ng-click="submitE()" />
            Ed: {{modele}}
        </div>
    </div>

When I use the directive to try to load a template, it does not appear to work.  I have tried multiple formats:

        <div oc-lazy-load="{name: 'e', files: ['/modules/rcm-js-lib/TEMP/e.js'], template: '/modules/rcm-js-lib/TEMP/etemplate.html'}">
            <div ng-include="modules/rcm-js-lib/TEMP/etemplate.html"></div>
        </div>

        <div oc-lazy-load="{name: 'e', files: ['/modules/rcm-js-lib/TEMP/e.js', '/modules/rcm-js-lib/TEMP/etemplate.html'], template: '/modules/rcm-js-lib/TEMP/etemplate.html'}">
        </div>

    <div oc-lazy-load="{name: 'e', files: ['/modules/rcm-js-lib/TEMP/e.js'], template: '/modules/rcm-js-lib/TEMP/etemplate.html'}">
    </div>

**Comment by Eun** [comment]
Would be good if this is in an example somewhere. So ppl stop asking about this.

**Comment by ocombe** [comment]
Agreed, I'm rewriting all the documentation on a brand new website, I'll add this :)

**Comment by ocombe** [comment]
Added to the new documentation website !
