### ISSUE TITLE
lazy loaded state, refresh page, localhost

### ISSUE THREAD

**Issue by edgar0011** [ocombe/ocLazyLoad#56]
Hi,

great job on lazy loading modules, really very useful.
I have on question, I think i followed the examples on ocLazyLoad and ui-router, everything wirks fine,
however I notice one issue, happening only on local, node.js app, on herokuaoo all works fine.
If I go to state that is resolved with ocLazyLoad for the first time all is well, if i refresh page, the controller for the state is not instantiated, this is console error:

Error: [ng:areq] http://errors.angularjs.org/1.2.14/ng/areq?p0=NotesController&p1=not%20aNaNunction%2C%20got%20undefined
    at Error (native)
    at https://code.angularjs.org/1.2.14/angular.min.js:6:450
    at xb (https://code.angularjs.org/1.2.14/angular.min.js:18:360)
    at Pa (https://code.angularjs.org/1.2.14/angular.min.js:18:447)
    at https://code.angularjs.org/1.2.14/angular.min.js:63:94
    at http://angular-ui.github.io/ui-router/release/angular-ui-router.js:2797:28
    at A (https://code.angularjs.org/1.2.14/angular.min.js:50:23)
    at h (https://code.angularjs.org/1.2.14/angular.min.js:43:83)
    at https://code.angularjs.org/1.2.14/angular.min.js:42:255
    at updateView (http://angular-ui.github.io/ui-router/release/angular-ui-router.js:2733:23) 

Just curious, it might be something with either order of exectution, or cache ?

the app is deployed here, http://ngproject.herokuapp.com/#/main, all sources are unminified, could you please take a look ?
the lazyloaded state is /notes, NotesModule.js.....

Thank you in dvance

Martin

**Comment by ngocdam** [comment]
Hi, it seems not to work properly on my localhost when refresh the page many times. I have  already return promise in resolve, below  is my router config (I also attach a full sample here):

`$.each(appConfig.usingModules, function(index, module) {
                if (typeof appConfig.moduleConfig != "undefined" && typeof appConfig.moduleConfig[module] != "undefined" && appConfig.moduleConfig[module]) {
                    $stateProvider.state(module, {
                        url: '/' + module,
                        templateUrl: 'modules/' + module + '/index.html',
                        resolve: {
                            load: function($ocLazyLoad) {
                                return $ocLazyLoad.load({
                                    name: module,
                                    files: appConfig.moduleConfig[module].dependencies
                                }).then(function() {});
                            }
                        }
                    });
                }
            });`
[fw.zip](https://github.com/ocombe/ocLazyLoad/files/258959/fw.zip)

Could you please help me to check this? Thank you very much.
