### ISSUE TITLE
Using ocLazyLoad with concatenate and minified files

### ISSUE THREAD

**Issue by chandermani** [ocombe/ocLazyLoad#88]
Hi,
The library works great with lazy loading modules.
I am looking for some guidance on how can we handle scenarios where while development we use separate script files but, for production combine and minify those scripts. So the config setup 

``` javascript
$ocLazyLoad.load({
    name: 'TestModule',
    files: ['testModule.js', 'testModuleCtrl.js', 'testModuleService.js']
});`

```

works fine development, but fails when content is concatenated.

Thanks,
Chandermani

**Comment by burakkilic** [comment]
+1

**Comment by SaurabhSharma45** [comment]
I have the same requirement.
Does anyone found the solution?

**Comment by dpundir** [comment]
any solution or workaround?

**Comment by ocombe** [comment]
It should work since version 1.0

**Comment by zeeshanjan82** [comment]
@ocombe I have code something like this
```js
return $ocLazyLoad.load({
			  name:'InkskillApp',
			  files:['public/js/controller/home.js','public/css/owl.carousel.css','public/js/owl.carousel.min.js']
			})
```
so I have js and css files loaded. I need to have a flag 'isProd' where it shld load the js files from minified js file and css from corresponding minified css file.
