### ISSUE TITLE
Param to indicate file type

### ISSUE THREAD

**Issue by Hubrus** [ocombe/ocLazyLoad#93]
Hi Olivier,

I've noticed that the loading of files is based on the file's extension, but in some particular cases, like asp.net mvc bundles, you don't have an extension. Therefore, in this case I would suggest to have a param to enforce how a file should be loaded (script, style or template).
The way I'm seeing this as being done, is to be able to specify not only strings in the files array, but also objects containing an url and a type properties.

Thanks!

**Comment by paulisme** [comment]
I'd like to second this for the same reason @Hubrus mentioned.  I'm bundling my CSS file using ASP.NET and the resulting URL does not have the .css file extension.

**Comment by BenBlazely** [comment]
Which of the following formats would be preferable?
```javascript
files: {
   css: [file1, file2, file3],
   js: [file1, file2],
   html: file1
}
```
or 
```javascript
files: [
  {path: file1, type: 'css'},
  {path: file2, type: 'css'},
  {path: file3, type: 'js'}
]
```
I'm leaning towards the former, grouping loads by type. Thoughts?

**Comment by paulisme** [comment]
How about allowing a file type hint as a prefix to the URL similar to the RequireJS plugin syntax?

files: [
    'css!http://example.com/styles',
    'js!http://example.com/scripts'
]

**Comment by ocombe** [comment]
Added in https://github.com/ocombe/ocLazyLoad/commit/725ceb9a51986b67a770de12b0cdd810e92cfb2d, thanks @BenBlazely !
