### ISSUE TITLE
How to use in Jasmine?

### ISSUE THREAD

**Issue by timpcc** [ocombe/ocLazyLoad#94]
I'd like to test a module which has a lazy loaded dependency using Jasmine 2.0. It loads fine in angular but I just get a 404 when I try to load the module in Jasmine. The module def looks like this:

```
angular.module('hap.activity.plugins.tools.buttontool', [
{
    name:'hap.activity.plugins.tools.statetool',
    files:['src/app/activity/tools/statetool/statetool.js']
}
]).factory('ButtonTool', ['StateTool', function(StateTool) {
}
```

I'm trying to inject it in Jasmine like this:

```
beforeEach(module('oc.lazyLoad'));
beforeEach(function(done){      
    inject(function($ocLazyLoad) {
        $ocLazyLoad.load({
            name:'hap.activity.plugins.tools.buttontool',
            files:['src/app/activity/plugins/tools/buttontool/buttontool.js']
        }).then(function(){
            dump("Loaded!");
            done();
        }, function(error){
            dump(error);
        });
    });
});
```

I just get an error:

```
WARN [web-server]: 404: /src/app/activity/plugins/tools/buttontool/buttontool.js
```

so it must be trying to load the module, but it doesn't work and then the async beforeEach times out.

I could just load the buttontool module as normal, except that it has the ocLazyLoad specific object dependency which angular doesn't understand.

Any idea what I'm doing wrong?

Thanks,
Tim

**Comment by DevilStudio** [comment]
Thank you, that is important for other service callback!

**Comment by gm2008** [comment]
Hello, ocombe, 
   I am running into same problem when doing unit test with Mocha. I've tried your solution of calling $rootScope.digest() seems. It seems still not resolved. Could you possibly have a look at this? 
Thanks

**Comment by nishantkmr** [comment]
I tried the $rootScope.digest() but it fails for modules that are loaded with AngularJS ModuleName instead of module file path.
